In [1]:
import pandas as pd
import importlib
import sys

PATH_TO_LIB = "XXX"  # PATH TO LIBRARY
sys.path.append(PATH_TO_LIB)

### В данной части протестим написанную библиотеку и доступные данные Мосбиржи.

Частично будем править либу (данный раздел - часть функционального тестирования).

Весь рабочий функционла содержится в класса MoexApi

In [83]:
import api_lib.main as api
import api_lib.dictionaries as _dictionar_
import api_lib.mixins as _mixins_

MOEX = api.MoexApi()

def reload_moex():
    importlib.reload(_dictionar_)
    importlib.reload(_mixins_)
    importlib.reload(api)
    global MOEX
    MOEX = api.MoexApi()

In [150]:
MOEX.help()

Для запроса данных используйте метод request!
Список базовых сущностей хранится в переменной 'available_entities'
Виды бумаг хранятся в переменной 'SECTYPE'
Срочность опциона хранится в переменной 'OPTION_SERIES_TYPE'
Все доступные API можно посмотреть вызвав all_api()
Описание API можно посмотреть вызвав api_description
Описание глобальной сущности можно получить вызвав description

In [142]:
# Методы и справочники: 
[data for data in dir(MOEX) if not data.startswith("_")]

['OPTION_SERIES_TYPE',
 'SECTYPE',
 'all_api',
 'api_description',
 'available_entities',
 'boardgroups',
 'boards',
 'datatypes',
 'description',
 'durations',
 'engines',
 'help',
 'indexids',
 'markets',
 'report_names',
 'request',
 'securitycollections',
 'securitygroups',
 'securitytypes',
 'sessions']

#### Базовые справочники. Используйте их для формирования запросов

In [147]:
for d in ['OPTION_SERIES_TYPE', 'SECTYPE', 'available_entities', 'boardgroups', 'boards', 
          'datatypes', 'durations', 'engines', 'indexids', 'markets', 'report_names', 
          'securitycollections', 'securitygroups', 'securitytypes', 'sessions']:
    print(d + ":")
    attr = getattr(MOEX, d)
    if isinstance(attr, pd.DataFrame):
        display(attr[:5])
        print()
    else:
        print(attr, "\n")

OPTION_SERIES_TYPE:
{'D': 'дневной', 'W': 'недельный', 'M': 'месячный', 'Q': 'квартальный'}

SECTYPE:
{'1': 'Акция обыкновенная', '2': 'Акция привилегированная', '3': 'Государственные облигации', '4': 'Региональные облигации', '5': 'Облигации центральных банков', '6': 'Корпоративные облигации', '7': 'Облигации МФО', '8': 'Биржевые облигации', '9': 'Паи открытых ПИФов', 'A': 'Паи интервальных ПИФов', 'B': 'Паи закрытых ПИФов', 'C': 'Муниципальные облигации', 'D': 'Депозитарные расписки', 'E': 'Бумаги иностранных инвестиционных фондов (ETF)', 'F': 'Ипотечный сертификат', 'G': 'Корзина бумаг', 'H': 'Доп. идентификатор списка', 'I': 'ETC (товарные инструменты)', 'J': 'Пай биржевого ПИФа (Exchange Investment Unit share)'}

available_entities:
['boardgroups', 'boards', 'datatypes', 'durations', 'engines', 'indexids', 'markets', 'report_names', 'securitycollections', 'securitygroups', 'securitytypes', 'sessions']

boardgroups:

,id,trade_engine_id,trade_engine_name,trade_engine_title,market_id,market_name,title,is_default,board_group_id,is_traded,is_order_driven,category
name,,,,,,,,,,,,
stock_index,9,1,stock,Фондовый рынок и рынок депозитов,5,index,Индексы,1,9,1,NaN,main
stock_index_inav,104,1,stock,Фондовый рынок и рынок депозитов,5,index,INAV,0,104,1,NaN,main
stock_index_mmix,155,1,stock,Фондовый рынок и рынок депозитов,5,index,Money Market IndeX,0,155,1,NaN,main
stock_index_namex,1028,1,stock,Фондовый рынок и рынок депозитов,5,index,Индексы НТБ,0,1028,1,NaN,main
stock_index_pf,1153,1,stock,Фондовый рынок и рынок депозитов,5,index,Ценовой фиксинг,0,1153,1,NaN,main

boards:

,id,board_group_id,engine_id,market_id,board_title,is_traded,has_candles,is_primary
boardid,,,,,,,,
TQIF,177,57,1,1,Т+: Паи - безадрес.,1,1,1
TQTF,178,57,1,1,Т+: ETF - безадрес.,1,1,1
TQBR,129,57,1,1,Т+: Акции и ДР - безадрес.,1,1,1
TQBS,130,57,1,1,Т+: А2-Акции и паи - безадрес.,0,1,1
TQNL,131,57,1,1,Т+: Б-Акции и паи - безадрес.,0,1,1

datatypes:
['securities', 'trades']

durations:

          duration  days     title hint
interval
1               60  None    минута   1м
10             600  None  10 минут  10м
60            3600  None       час   1ч
24           86400  None      день   1д
7           604800  None    неделя   1н

engines:

           id                             title
name
stock       1  Фондовый рынок и рынок депозитов
state       2            Рынок ГЦБ (размещение)
currency    3                    Валютный рынок
futures     4                     Срочный рынок
commodity   5                    Товарный рынок

indexids:

                     shortname        from        till
indexid
IMOEX          Индекс МосБиржи  2001-01-03  2023-05-31
MOEX10      Индекс МосБиржи 10  2008-05-27  2023-05-31
RTSI                Индекс РТС  2009-09-30  2023-05-31
MOEXBC    Индекс голубых фишек  2010-01-14  2023-05-31
MOEXBMI  Индекс широкого рынка  2011-12-30  2023-05-31

markets:

,id,trade_engine_id,trade_engine_name,trade_engine_title,market_title,market_id,marketplace,is_otc,has_history_files,has_history_trades_files,has_trades,has_history,has_candles,has_orderbook,has_tradingsession,has_extra_yields,has_delay
market_name,,,,,,,,,,,,,,,,,
index,5,1,stock,Фондовый рынок и рынок депозитов,Индексы фондового рынка,5,INDICES,0,1.0,0.0,1.0,1.0,1,0.0,1,0,0
shares,1,1,stock,Фондовый рынок и рынок депозитов,Рынок акций,1,MXSE,0,1.0,1.0,1.0,1.0,1,1.0,1,0,1
bonds,2,1,stock,Фондовый рынок и рынок депозитов,Рынок облигаций,2,MXSE,0,1.0,1.0,1.0,1.0,1,1.0,1,1,1
ndm,4,1,stock,Фондовый рынок и рынок депозитов,Режим переговорных сделок,4,None,0,1.0,1.0,1.0,1.0,0,0.0,1,1,1
otc,29,1,stock,Фондовый рынок и рынок депозитов,ОТС,29,None,0,0.0,0.0,0.0,1.0,0,0.0,0,0,0

report_names:

                                                               description
report_name
numtrades                Информация о количестве договоров по инструмен...
participants             Информация о количестве лиц, имеющих открытые ...
openpositions            Информация об открытых позициях по инструмента...
expirationparticipants   Информация о количестве лиц, имеющих открытые ...
expirationopenpositions  Информация об объеме открытых позиций по догов...

securitycollections:

,id,title,security_group_id
name,,,
stock_index_all,72,Все индексы,12
stock_index_shares,213,Основные индексы акций,12
stock_index_shares_sectoral,210,Отраслевые индексы акций,12
stock_index_total_return,249,Индексы акций полной доходности,12
stock_index_shares_thematic,211,Тематические индексы акций,12

securitygroups:

               id      title  is_hidden
name
stock_index    12    Индексы          0
stock_shares    4      Акции          0
stock_bonds     3  Облигации          0
currency_selt   9     Валюта          0
futures_forts  10   Фьючерсы          0

securitytypes:

,id,trade_engine_id,trade_engine_name,trade_engine_title,security_type_title,security_group_name,stock_type
security_type_name,,,,,,,
common_share,3,1,stock,Фондовый рынок и рынок депозитов,Акция обыкновенная,stock_shares,1
preferred_share,1,1,stock,Фондовый рынок и рынок депозитов,Акция привилегированная,stock_shares,2
depositary_receipt,51,1,stock,Фондовый рынок и рынок депозитов,Депозитарная расписка,stock_dr,D
ofz_bond,54,1,stock,Фондовый рынок и рынок депозитов,Государственная облигация,stock_bonds,3
cb_bond,4,1,stock,Фондовый рынок и рынок депозитов,Облигация центрального банка,stock_bonds,5

sessions:

                 description
sessions
1            Основная сессия
2            Вечерняя сессия
3         Итого (все сессии)
0            Утренняя сессия

In [159]:
# Доступные методы: ['all_api', 'api_description', 'description', 'request']
help(MOEX.description)

Help on method description in module api_lib.main:

description(entity: str, name) -> str method of api_lib.main.MoexApi instance
    Получить описание сущности.
    :param entity: тип сущности в единственном числе.
    :param name: имя сущности.
    :return: Описание сущности.

In [168]:
print(MOEX.description("securitytype", "depositary_receipt"))
print(MOEX.description("securitygroup", "currency_selt"))
print(MOEX.description("securitycollection", "stock_index_total_return"))
print(MOEX.description("market", "ndm"))

Депозитарная расписка
Валюта
Индексы акций полной доходности
                          market_title
market_name
ndm          Режим переговорных сделок
ndm                Внесистемные сделки
ndm                     Облигации c ЦК

In [165]:
print(MOEX.description("blablalbla", "qwert"))

NameError: Entity 'blablalbla' is not found!

#### Ниже список всех доступных поинтов. ID поинта используется для запроса!

In [177]:
MOEX.all_api()

5 Список бумаг торгуемых на московской бирже.
13 Получить спецификацию инструмента.
24 Получить сводные обороты по рынкам
26 Получить интервал дат, доступных в истории для рынка по заданному режиму торгов.
28 Получить глобальные справочники ISS.
32 Получить таблицу инструментов по режиму торгов.
33 Получить таблицу инструментов торговой сессии по рынку в целом.
34 Получить все сделки по выбранному режиму торгов.
35 Получить все сделки рынка.
40 Получить доступные торговые системы.
41 Получить описание и режим работы торговой системы.
42 Получить список рынков торговой системы.
43 Получить справочник режимов торгов рынка.
44 Получить описание: словарь доступных режимов торгов, описание полей публикуемых таблиц данных и т.д.
45 Получить справочник групп режимов торгов.
46 Получить свечи указанного инструмента по выбранному режиму торгов.
48 Получить период дат рассчитанных свечей.
49 Получить описание режима торгов.
50 Получить описание группы режимов торгов.
52 Получить данные по конкретному инструменту рынка.
53 Получить данные по указанному инструменту на выбранном режиме торгов.
55 Получить сделки по инструменту.
56 Получить все сделки указанного инструмента по выбранному режиму торгов.
61 Получить интервал дат в истории для указанного рынка и бумаги.
62 Получить историю по всем бумагам на рынке за одну дату.
63 Получить историю по одной бумаге на рынке за интервал дат.
64 Получить историю торгов для всех бумаг на указанном режиме торгов отфильтрованных по дате.
65 Получить историю торгов для указанной бумаги на указанном режиме торгов за указанный интервал дат.
66 Получить интервал дат в истории, за которые доступна указанная бумага на рынке на указанном режиме торгов.
83 Получить даты, за которые доступны данные на указанных рынке и торговой системе.
89 Получить данные по кривой бескупонной доходности(Прекращены расчеты с 2018-01-03)
95 Получить текущее значение оборотов торговой сессии по рынкам торговой системы
96 Получить текущее значение оборота по рынку
100 Получить описание полей для запросов оборотов по рынку/торговой системе.
114 Список годов, за которые существуют ссылки на файлы с архивом сделок и исторической биржевой информацией. datatype может принимать значения securities или trades.
115 Список месяцев в году, за которые существуют ссылки на файлы с архивом сделок и исторической биржевой информацией. datatype может принимать значения securities или trades.
118 Список неторгуемых инструментов с указанием интервалов торгуемости по режимам
119 Получить данные по листингу бумаг в историческом разрезе по указанному режиму
123 Информация по техническому изменению торговых кодов
127 Группы ценных бумаг
128 Группа ценных бумаг
129 Коллекции ценных бумаг входящие в группу
130 Коллекция ценных бумаг входящие в группу
131 Описание инструментов
134 Показатели для определения критериев существенного отклонения
146 Индексы фондового рынка
147 Аналитические показатели за дату
148 Список тикеров за все время торгов
155 Получить свечи указанного инструмента по дефолтной группе режимов.
156 Интервалы свечей, доступных к запросу по ФИ
157 Получить свечи указанного инструмента по выбранной группе режимов торгов.
159 Капитализация фондового рынка
160 Список индексов в которые входит бумага
161 Список режимов обобщенной информации по фондовому рынку
162 Обобщенная информация по фондовому рынку
165 РЕПО ГЦБ объемы (УСТАРЕЛО)
166 РЕПО ГЦБ детали (УСТАРЕЛО)
168 Курсы ЦБРФ
169 Средневзвешенные ставки по операциям центрального банка
171 Cписок акций, по которым рассчитывается рыночная котировка
172 Коэффициенты корелляции фондового рынка
178 Ставки РЕПО аукционов (ГЦБ)
179 Описание полей для запроса ставок РЕПО аукционов (ГЦБ)
191 Новости биржи
192 Новость сайта
193 Мероприятия биржи
194 Контент мероприятия биржи
195 Агрегированные показатели рынка облигаций
196 Описание колонок по агрегированным показетелям рынка бондов
205 Описание колонок бумаг входящих в индекс
214 Агрегированные итоги торгов за дату по рынкам
634 Кривые безкупонной доходности
649 Текущие цены бумаг
711 Индикативные курсы валют срочного рынка
712 Индикативный курс валют срочного рынка
715 Фиксинги Московской биржи
716 Фиксинги Московской биржи
758 Справочник дроблений и консолидаций бумаг фондового рынка
767 Сводная статистика по клиентам с самым высоким нетто-потоком. Детали https://fs.moex.com/f/10374/netflow2-demo-en.html
769 Сводная статистика по клиентам с самым высоким нетто-потоком. Запрос возможен с лагом -15 дней от текущего для 1 эшелона. Детали https://fs.moex.com/f/10374/netflow2-demo-en.html
783 История изменения параметров КБД (Кривая Бескупоной Доходности).
791 Получить историю рассчитанных доходностей для всех бумаг на указанном режиме торгов отфильтрованных по дате.
793 Получить историю доходностей по одной бумаге на рынке за интервал дат.
795 Получить историю доходностей для всех бумаг на указанном режиме торгов отфильтрованных по дате.
797 Получить историю доходностей для указанной бумаги на указанном режиме торгов за указанный интервал дат.
807 Сводные остатки по фьючерсам на физ. и юр. лица.
809 Сводные остатки по фьючерсам на физ. и юр. лица. Запрос возможен с лагом -15 дней, по коду фьючерса
811 Список сессий доступных в итогах торгов. Только для фондового рынка!
813 Получить историю по всем бумагам на рынке за одну дату.
815 Получить историю торгов для указанной бумаги на указанном режиме торгов за указанный интервал дат.
817 Получить историю по одной бумаге на рынке за интервал дат.
821 Получить историю торгов для всех бумаг на указанном режиме торгов отфильтрованных по дате.
823 Промежуточные "Итоги дня".Только для фондового рынка
839 Бюллетени для индексов
843 RUSFAR расшифровка показателей
859 Будущие ставки для ценообразования нестандартных инструментов (деривативов)
861 Будущие ставки для ценообразования нестандартных инструментов (деривативов)
873 Опционные серии
877 Опционные серии
879 Объем торгов для опционной серии
881 Доска опционов
883 Открытые позиции по опционной серии
885 Объем торгов для опционной серии
923 Календарь расчетных дней
927 Своп-кривые на рынке СПФИ
933 НКД на конец месяца

In [178]:
help(MOEX.api_description)

Help on function api_description in module api_lib.main:

api_description(api_id: Union[str, int], full_description: bool = False)
    Описание эндпоинтов. Используйте данный метод как справочник для формирования запросов.
    :param api_id: id эндпоинта.
    :param full_description: True/False. Дополнительно вернет ссылку на описание эндпоинта и его template.
    :return: Описание возвращаемых сущностей, требуемых сущностей и параметров запроса.

### Метод api_description вернет описание поинта. В нем будут перечислены доступные параметры, требуемые сущности и прочая полезная инфа

In [179]:
MOEX.api_description(5, full_description=True)

5: Список бумаг торгуемых на московской бирже.

Возвращаемые поинтом данные:
securities: Список бумаг торгуемых на московской бирже.

Параметры запроса:
``q``: Поиск инструмента по части Кода, Названию, ISIN, Идентификатору Эмитента, Номеру гос.регистрации.
Например: https://iss.moex.com/iss/securities.xml?q=MOEX
Слова длиной менее трёх букв игнорируются. Если параметром передано два слова через пробел. То каждое должно быть длиной не менее трёх букв..
``engine``:
``is_trading``:
``market``:
``group_by``: Группировать выводимый результат по полю. Доступны значения group и type..
``limit``: Количество выводимых инструментов (5, 10, 20,100). Значение по умолчанию: 100
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/5
Темплейт: http://iss.moex.com/iss/securities

In [181]:
MOEX.api_description(56, full_description=True)

56: Получить все сделки указанного инструмента по выбранному режиму торгов.
Глобальные сущности запроса: ['engine', 'market', 'board', 'security']

Возвращаемые поинтом данные:
trades: Перечень сделок
dataversion: Версионность данных.
trades_yields: Дополнительные доходности для сделок

Параметры запроса:
``tradeno``: Номер сделки, с которого следует начать возвращать данные.
В данных возвращаются сделки начиная с номера переданной сделки переданого в параметре tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".

Сделки возвращаются в порядке их заключения. На срочном рынке номер более поздней сделки может быть менее номера предыдущей.
. Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH.
``limit``: Количество строк в данных. Доступные значения: 1, 10, 100, 1000, 5000. Значение по умолчанию: 5000
``reversed``: обратный порядок сортировки. Значение по умолчанию: 0
``previous_session``: Сделки предыдущей сессии для forts и options рынков.
И для индексов.
. Значение по умолчанию: 0
``recno``: Только для срочного рынка (FORTS + OPTIONS).
Фильтрация по полю RECNO (в порядке заключения сделок).

Заменяет собой фильтр tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".
. Значение по умолчанию: 0
``next_trade``: Не включать текущую сделку в выдачу.. Значение по умолчанию: 0
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0
``yielddatetype``: Тип доходности. Возможные значения
- MBS
- MATDATE
- OFFERDATE.

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/56
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards/{board}/securities/{security}/trades

## Перейдем к части самих запросов с MOEX API. За запросы отвечает метод request

Данный метод проверяет корректность запрошенных параметров и сущностей (вернет ошибку, если что-то указанно некорректно), сформирует корректный GET запрос и соберет результат в единый фрейм если у эндпоинта пристуствует пагинация (возвращает ограниченное число записей).

In [128]:
help(MOEX.request)

Help on method request in module api_lib.main:

request(api_id: Union[int, str], only_market_data: bool = False, blocks: List[str] = None, **kwargs: Any) -> Union[pandas.core.frame.DataFrame, Dict[str, pandas.core.frame.DataFrame]] method of api_lib.main.MoexApi instance
    Запрос данных по API Мосбиржи:
    :param api_id: указывается id поинта запроса данных;
    :param only_market_data: включать или нет непосредственно рыночные данные. По умолчанию не указываем;
    :param blocks: ответ может содержать несколько блоков данных и этот параметр позволяет выбрать только нужные.
    См. список возвращаемых данных в справочнике эндпоинтов.
    :param kwargs:
    1. Обязательно указываем значения всех требуемых глобальных сущностей;
    2. Указываем значения параметров;
        2.1. Если имя параметра совпадает с именем глобальной сущности, то к имени параметра добавляем префикс 'P_',
        например, "P_market" для параметра "market";
        2.2. Если значений параметров несколько, передаем их в виде списка, например, securities = ["GAZP", "LKOH"]
        2.3. Если имя параметра является ключевым атрибутом python, добавьте к имени '_', например: _from.
        2.4. Если в имени параметра содержится '.' (точка), замените ее на двойное подчеркивание, например:
        iss.reverse -> iss__reverse
    3. Если хотим указать атрибутный состав полей для блока, то к имени блока добавляем префикс
    'COLUMNS_'. Названия атрибутов перечисляем в списке. Например, COLUMNS_boardgroups = ["slug", "is_default"].
    :return: Если запрашивается только одна сущность то вернется фрейм данных. Если много, то в словаре, где
    ключом является имя сущности.

In [10]:
FULL_ID = sorted(map(int, api.GLOBAL_API.keys()))

### Базовый пример запроса:

1. Смотрим описание поинта.
2. Формируем запрос. Указываем id поинта, имя инструмента, торгуемость, сортируем по типу, указываем нужные нам колонки.
3. Играем с другими параметрами (в т.ч. и с корявыми)

In [188]:
MOEX.api_description(5)

5: Список бумаг торгуемых на московской бирже.

Возвращаемые поинтом данные:
securities: Список бумаг торгуемых на московской бирже.

Параметры запроса:
``q``: Поиск инструмента по части Кода, Названию, ISIN, Идентификатору Эмитента, Номеру гос.регистрации.
Например: https://iss.moex.com/iss/securities.xml?q=MOEX
Слова длиной менее трёх букв игнорируются. Если параметром передано два слова через пробел. То каждое должно быть длиной не менее трёх букв..
``engine``:
``is_trading``:
``market``:
``group_by``: Группировать выводимый результат по полю. Доступны значения group и type..
``limit``: Количество выводимых инструментов (5, 10, 20,100). Значение по умолчанию: 100
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0

Эндпоинт возвращает ограниченное количество записей

In [195]:
df_nornik = MOEX.request(
    5, 
    q='Норильский', 
    is_trading=1, 
    group_by="type", 
    COLUMNS_securities=["secid", "shortname", "isin", "type", "group", "primary_boardid"]
)
df_nornik

,secid,shortname,isin,type,group,primary_boardid
0,GMKN,ГМКНорНик,RU0007288411,common_share,stock_shares,TQBR
1,RU000A105A61,НорНикБ1P2,RU000A105A61,exchange_bond,stock_bonds,TQCB
2,RU000A100VQ6,НорНикБ1P1,RU000A100VQ6,exchange_bond,stock_bonds,TQCB
3,RU000A1069N8,НорНик БО9,RU000A1069N8,exchange_bond,stock_bonds,TQCB
4,RU000A105NL3,НорНикБ1P6,RU000A105NL3,exchange_bond,stock_bonds,TQOY
...,...,...,...,...,...,...
1256,GK9750BR3,GMKN-6.23M140623PA9750,None,option,futures_options,ROPD
1257,GK9750BS3,GMKN-9.23M190723PA9750,None,option,futures_options,ROPD
1258,GK9750BT3,GMKN-9.23M160823PA9750,None,option,futures_options,ROPD
1259,GK9750BU3,GMKN-9.23M200923PA9750,None,option,futures_options,ROPD
1260,GK9750BX3,GMKN-12.23M201223PA9750,None,option,futures_options,ROPD

In [196]:
MOEX.request(
    5, 
    q='Арсагера', 
)

,id,secid,shortname,regnumber,name,isin,is_traded,emitent_id,emitent_title,emitent_inn,emitent_okpo,gosreg,type,group,primary_boardid,marketprice_boardid
0,6115,ARSA,Арсагера,1-01-03163-D,УК Арсагера ПАО-ао,RU000A0JP0Q7,1,1937.0,"публичное акционерное общество ""Управляющая ко...",7840303927,73405555,1-01-03163-D,common_share,stock_shares,TQBR,TQBR
1,3259,RU000A0HGNG6,АрсагераФА,0363-75409054,ОПИФ Арсагера - фонд акций,RU000A0HGNG6,1,1937.0,"публичное акционерное общество ""Управляющая ко...",7840303927,73405555,0363-75409054,public_ppif,stock_ppif,TQIF,TQIF
2,6014,ARSA-001D,Арсагера,1-01-03163-D-001D,УК Арсагера ОАО-ао,RU000A0JP0Q7,0,NaN,None,None,None,1-01-03163-D-001D,common_share,stock_shares,EQNE,None
3,3260,RU000A0HGNH4,ПИФАрсСИ,0364-75409132,Арсагера фонд смеш. инвестиц.,RU000A0HGNH4,0,1937.0,"публичное акционерное общество ""Управляющая ко...",7840303927,73405555,0364-75409132,public_ppif,stock_ppif,TQIF,None
4,3275,RU000A0JC5V1,ПИФАрсЖС,0402-75409534,Арсагера- жилищное строит. ПИФ,RU000A0JC5V1,0,1937.0,"публичное акционерное общество ""Управляющая ко...",7840303927,73405555,0402-75409534,private_ppif,stock_ppif,TQIF,TQIF
5,5925,RU000A0JPJ84,ПИФАрсЖД,0852-75409273,"ПИФ ""Арсагера ЖД"" УК Арсагера",RU000A0JPJ84,0,1937.0,"публичное акционерное общество ""Управляющая ко...",7840303927,73405555,0852-75409273,private_ppif,stock_ppif,TQIF,None
6,6054,RU000A0JPMD2,ПИФАрc6.4,0439-75408664,Арсагера-акции 6.4 ПИФ,RU000A0JPMD2,0,1937.0,"публичное акционерное общество ""Управляющая ко...",7840303927,73405555,0439-75408664,interval_ppif,stock_ppif,TQIF,None

In [197]:
MOEX.request(
    5, 
    q='Арсагера', 
    is_trading=1, 
    group_by="group", 
    COLUMNS_securities=["secid", "shortname", "is_traded", "isin", "type", "group", "primary_boardid"]
)

,secid,shortname,is_traded,isin,type,group,primary_boardid
0,ARSA,Арсагера,1,RU000A0JP0Q7,common_share,stock_shares,TQBR
1,RU000A0HGNG6,АрсагераФА,1,RU000A0HGNG6,public_ppif,stock_ppif,TQIF

In [199]:
MOEX.request(
    5, 
    q='Арсагера', 
    start=5
)

,id,secid,shortname,regnumber,name,isin,is_traded,emitent_id,emitent_title,emitent_inn,emitent_okpo,gosreg,type,group,primary_boardid,marketprice_boardid
0,5925,RU000A0JPJ84,ПИФАрсЖД,0852-75409273,"ПИФ ""Арсагера ЖД"" УК Арсагера",RU000A0JPJ84,0,1937,"публичное акционерное общество ""Управляющая ко...",7840303927,73405555,0852-75409273,private_ppif,stock_ppif,TQIF,None
1,6054,RU000A0JPMD2,ПИФАрc6.4,0439-75408664,Арсагера-акции 6.4 ПИФ,RU000A0JPMD2,0,1937,"публичное акционерное общество ""Управляющая ко...",7840303927,73405555,0439-75408664,interval_ppif,stock_ppif,TQIF,None

In [198]:
MOEX.request(
    5, 
    q='Арсагера', 
    bad_param = "123"
)

KeyError: "Переданы неопределенные для API параметры: {'bad_param': '123'}"

In [200]:
MOEX.request(
    5, 
    q='A', 
)

ValueError: Запрос инструментов длиной менее трёх букв игнорируются.

# На этом ознакомление с библиотекой закончено. Перейдем к изучению поинтов.

In [11]:
FULL_ID.remove(5)

In [9]:
def print_df(result):
    if isinstance(result, pd.DataFrame):
        display(result[:10])
        return
    for key, df in result.items():
        print(key)
        display(df[:10])

In [223]:
MOEX.api_description(FULL_ID[0], True)

13: Получить спецификацию инструмента.
Глобальные сущности запроса: ['security']

Возвращаемые поинтом данные:
description: Описание инструментов
boards: Режимы, на которых торгуется инструмент

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/13
Темплейт: http://iss.moex.com/iss/securities/{security}

In [228]:
result = MOEX.request(13, security="GMKN")
print_df(result)

description

,name,title,value,type,sort_order,is_hidden,precision
0,SECID,Код ценной бумаги,GMKN,string,1,0,NaN
1,NAME,Полное наименование,"ГМК ""Нор.Никель"" ПАО ао",string,3,0,NaN
2,SHORTNAME,Краткое наименование,ГМКНорНик,string,4,0,NaN
3,ISIN,ISIN код,RU0007288411,string,5,0,NaN
4,REGNUMBER,Номер государственной регистрации,1-01-40155-F,string,6,0,NaN
5,ISSUESIZE,Объем выпуска,152863397,number,7,0,0.0
6,FACEVALUE,Номинальная стоимость,1,number,8,0,2.0
7,FACEUNIT,Валюта номинала,SUR,string,9,0,NaN
8,ISSUEDATE,Дата начала торгов,2006-12-26,date,10,0,NaN
9,LATNAME,Английское наименование,NorNickel GMK,string,11,1,NaN

boards

,secid,boardid,title,board_group_id,market_id,market,engine_id,engine,is_traded,decimals,history_from,history_till,listed_from,listed_till,is_primary,currencyid
0,GMKN,TQBR,Т+: Акции и ДР - безадрес.,57,1,shares,1,stock,1,0,2014-06-09,2023-05-31,2014-06-09,2023-06-01,1,RUB
1,GMKN,TQBS,Т+: А2-Акции и паи - безадрес.,57,1,shares,1,stock,0,0,2013-03-25,2014-06-06,2013-03-25,2014-06-06,0,RUB
2,GMKN,EQBR,Основной режим: А1-Акции и паи - безадрес.,6,1,shares,1,stock,0,0,2010-04-28,2011-08-11,2010-04-28,2011-08-11,0,RUB
3,GMKN,EQBS,Основной режим: А2-Акции и паи - безадрес.,6,1,shares,1,stock,0,0,2011-08-12,2013-08-30,2011-08-12,2013-08-30,0,RUB
4,GMKN,EQNL,Основной режим: Б-Акции и паи - безадрес.,6,1,shares,1,stock,0,2,2006-12-26,2010-04-27,2006-12-26,2010-04-27,0,RUB
5,GMKN,SPEQ,Поставка по СК (акции),125,1,shares,1,stock,1,2,2018-06-29,2023-03-17,2018-06-29,2023-06-01,0,RUB
6,GMKN,TQDP,Крупные пакеты - Акции - безадрес.,42,1,shares,1,stock,0,0,None,None,2019-03-04,2023-02-15,0,RUB
7,GMKN,EQDP,Крупные пакеты - Акции - безадрес.,42,1,shares,1,stock,0,0,2011-12-12,2019-03-01,2011-12-12,2019-03-01,0,RUB
8,GMKN,RPMO,РЕПО-М - адрес.,201,3,repo,1,stock,1,4,2019-04-22,2023-05-31,2019-04-22,2023-06-01,0,RUB
9,GMKN,PTEQ,РПС с ЦК: Акции и ДР - адрес.,59,4,ndm,1,stock,1,0,2014-06-09,2023-05-31,2014-06-09,2023-06-01,0,RUB

In [229]:
result = MOEX.request(13, security="GMKN", blocks=["description"])
print_df(result)

,name,title,value,type,sort_order,is_hidden,precision
0,SECID,Код ценной бумаги,GMKN,string,1,0,NaN
1,NAME,Полное наименование,"ГМК ""Нор.Никель"" ПАО ао",string,3,0,NaN
2,SHORTNAME,Краткое наименование,ГМКНорНик,string,4,0,NaN
3,ISIN,ISIN код,RU0007288411,string,5,0,NaN
4,REGNUMBER,Номер государственной регистрации,1-01-40155-F,string,6,0,NaN
5,ISSUESIZE,Объем выпуска,152863397,number,7,0,0.0
6,FACEVALUE,Номинальная стоимость,1,number,8,0,2.0
7,FACEUNIT,Валюта номинала,SUR,string,9,0,NaN
8,ISSUEDATE,Дата начала торгов,2006-12-26,date,10,0,NaN
9,LATNAME,Английское наименование,NorNickel GMK,string,11,1,NaN

In [12]:
FULL_ID.remove(13)

In [231]:
MOEX.api_description(FULL_ID[0], True)

24: Получить сводные обороты по рынкам

Возвращаемые поинтом данные:
turnovers: Обороты рынков
turnoversprevdate: Обороты рынков за предыдущий торговый день

Параметры запроса:
``date``: Значение по умолчанию: today

Детали: http://iss.moex.com/iss/reference/24
Темплейт: http://iss.moex.com/iss/turnovers

In [233]:
result = MOEX.request(24, date="2023-05-31", 
                      COLUMNS_turnovers=["NAME", "VALTODAY", "NUMTRADES", "TITLE"],
                      COLUMNS_turnoversprevdate=["NAME", "VALTODAY_USD", "NUMTRADES"])
print_df(result)

turnovers

        NAME      VALTODAY  NUMTRADES                             TITLE
0      stock  2.825577e+06  3198312.0  Фондовый рынок и рынок депозитов
1   currency  1.012673e+06   279200.0                    Валютный рынок
2    futures  3.010214e+05  1264329.0                     Срочный рынок
3  commodity           NaN        NaN                    Товарный рынок
4       agro  2.533306e+02       28.0                              Агро
5        otc  4.385368e+03      200.0                          ОТС с ЦК
6     TOTALS  4.143910e+06  4742069.0         Всего по Московской Бирже

turnoversprevdate

        NAME  VALTODAY_USD  NUMTRADES
0      stock  35473.896838  3988636.0
1   currency  13362.898572   295446.0
2    futures   3587.763843  1294999.0
3  commodity           NaN        NaN
4       agro      5.015068       39.0
5        otc     26.141840      253.0
6     TOTALS  52455.716161  5579373.0

In [13]:
FULL_ID.remove(24)

In [235]:
MOEX.api_description(FULL_ID[0], True)

26: Получить интервал дат, доступных в истории для рынка по заданному режиму торгов.
Глобальные сущности запроса: ['engine', 'market', 'board']

Возвращаемые поинтом данные:
dates: Интервал дат, доступных в истории.

Параметры запроса:
``interim``: Показать интервал дат промежуточных итогов торгов (только для валютного рынка). Значение по умолчанию: 0
``tradingsession``: Показать данные только за необходимую сессию (только для фондового рынка)
  0 - Утренняя
  1 - Основная
  2 - Вечерняя
  3 - Итого.

Детали: http://iss.moex.com/iss/reference/26
Темплейт: http://iss.moex.com/iss/history/engines/{engine}/markets/{market}/boards/{board}/dates

In [15]:
reload_moex()

In [17]:
result = MOEX.request(26, engine="stock", market="shares", board="TQBR", tradingsession=0)
print_df(result)

         from        till
0  2021-12-06  2022-02-24

In [18]:
FULL_ID.remove(26)

In [19]:
MOEX.api_description(FULL_ID[0], True)

28: Получить глобальные справочники ISS.

Возвращаемые поинтом данные:
engines: Список доступных торговых систем
markets: Справочник доступных рынков и их атрибуты.
Описание дополнительных полей:
  - is_otc - Внебиржевой рынок.
  - has_history_files - Формируются файлы с итогами торгов.
  - has_history_trades_files - Формируются файлы с реестрами сделок.
  - has_trades - Есть сделки внутри дня.
  - has_history - Есть итоги торгов.
  - has_candles - Для рынка есть свечки.
  - has_orderbook - Есть стаканы заявок.
  - has_tradingsession - Наличие дополнительных сессий у рынка.
  - has_extra_yields - Для рынка рассчитываются дополнительные доходности.
  - has_delay - Для рынка не предусмотрена задержка данных.
boards: Справочник режимов торгов
boardgroups: Справочник групп режимов торгов.
Расшифровка поля - "category" -> https://iss.moex.com/iss/index/handbooks/boardgroups_category.xml
durations: Справочник доступных расчетных интервалов свечей в формате HLOCV
securitytypes:
securitygroups:
securitycollections:

Параметры запроса:
``engine``:
``is_traded``: Показывать торгуемые только торгующиеся в настоящий момент группы режимов торгов:
is_traded=1. Значение по умолчанию: 0
``hide_inactive``: Значение по умолчанию: 0
``securitygroups``:
``trade_engine``:

Детали: http://iss.moex.com/iss/reference/28
Темплейт: http://iss.moex.com/iss/index

In [21]:
# Данные уже в справочнике объекта MOEX. В детали лезть нет смысла
result = MOEX.request(28)
print_df(result)

engines

     id           name                             title
0     1          stock  Фондовый рынок и рынок депозитов
1     2          state            Рынок ГЦБ (размещение)
2     3       currency                    Валютный рынок
3     4        futures                     Срочный рынок
4     5      commodity                    Товарный рынок
5     6  interventions              Товарные интервенции
6     7       offboard                       ОТС-система
7     9           agro                              Агро
8  1012            otc                          ОТС с ЦК

markets

,id,trade_engine_id,trade_engine_name,trade_engine_title,market_name,market_title,market_id,marketplace,is_otc,has_history_files,has_history_trades_files,has_trades,has_history,has_candles,has_orderbook,has_tradingsession,has_extra_yields,has_delay
0,5,1,stock,Фондовый рынок и рынок депозитов,index,Индексы фондового рынка,5,INDICES,0,1.0,0.0,1.0,1.0,1,0.0,1,0,0
1,1,1,stock,Фондовый рынок и рынок депозитов,shares,Рынок акций,1,MXSE,0,1.0,1.0,1.0,1.0,1,1.0,1,0,1
2,2,1,stock,Фондовый рынок и рынок депозитов,bonds,Рынок облигаций,2,MXSE,0,1.0,1.0,1.0,1.0,1,1.0,1,1,1
3,4,1,stock,Фондовый рынок и рынок депозитов,ndm,Режим переговорных сделок,4,None,0,1.0,1.0,1.0,1.0,0,0.0,1,1,1
4,29,1,stock,Фондовый рынок и рынок депозитов,otc,ОТС,29,None,0,0.0,0.0,0.0,1.0,0,0.0,0,0,0
5,27,1,stock,Фондовый рынок и рынок депозитов,ccp,РЕПО с ЦК,27,MXSE,0,1.0,1.0,1.0,1.0,1,1.0,1,0,1
6,35,1,stock,Фондовый рынок и рынок депозитов,deposit,Депозиты с ЦК,35,None,0,1.0,0.0,0.0,1.0,0,0.0,0,0,0
7,3,1,stock,Фондовый рынок и рынок депозитов,repo,Рынок сделок РЕПО,3,None,0,1.0,1.0,1.0,1.0,0,0.0,1,0,1
8,28,1,stock,Фондовый рынок и рынок депозитов,qnv,Квал. инвесторы,28,None,0,1.0,1.0,1.0,1.0,1,0.0,0,0,1
9,36,1,stock,Фондовый рынок и рынок депозитов,mamc,Мультивалютный рынок смешанных активов,36,None,0,1.0,1.0,1.0,1.0,0,0.0,1,0,1

boards

,id,board_group_id,engine_id,market_id,boardid,board_title,is_traded,has_candles,is_primary
0,177,57,1,1,TQIF,Т+: Паи - безадрес.,1,1,1
1,178,57,1,1,TQTF,Т+: ETF - безадрес.,1,1,1
2,129,57,1,1,TQBR,Т+: Акции и ДР - безадрес.,1,1,1
3,130,57,1,1,TQBS,Т+: А2-Акции и паи - безадрес.,0,1,1
4,131,57,1,1,TQNL,Т+: Б-Акции и паи - безадрес.,0,1,1
5,132,57,1,1,TQLV,Т+: В-Акции и ДР - безадрес.,0,1,1
6,133,57,1,1,TQLI,Т+: И-Акции - безадрес.,0,1,1
7,134,57,1,1,TQNE,"Т+: Акции, паи и ДР внесписочные - безадрес.",0,1,1
8,158,57,1,1,TQDE,Т+: Акции Д - безадрес.,0,1,1
9,401,57,1,1,TQPI,Т+: Акции ПИР - безадрес.,1,1,1

boardgroups

,id,trade_engine_id,trade_engine_name,trade_engine_title,market_id,market_name,name,title,is_default,board_group_id,is_traded,is_order_driven,category
0,9,1,stock,Фондовый рынок и рынок депозитов,5,index,stock_index,Индексы,1,9,1,NaN,main
1,104,1,stock,Фондовый рынок и рынок депозитов,5,index,stock_index_inav,INAV,0,104,1,NaN,main
2,155,1,stock,Фондовый рынок и рынок депозитов,5,index,stock_index_mmix,Money Market IndeX,0,155,1,NaN,main
3,1028,1,stock,Фондовый рынок и рынок депозитов,5,index,stock_index_namex,Индексы НТБ,0,1028,1,NaN,main
4,1153,1,stock,Фондовый рынок и рынок депозитов,5,index,stock_index_pf,Ценовой фиксинг,0,1153,1,NaN,main
5,287,1,stock,Фондовый рынок и рынок депозитов,5,index,stock_index_sdfi,Индексы СПФИ,0,287,1,NaN,main
6,57,1,stock,Фондовый рынок и рынок депозитов,1,shares,stock_shares_tplus,Т+: Основной режим - безадрес.,1,57,1,1.0,main
7,156,1,stock,Фондовый рынок и рынок депозитов,1,shares,stock_shares_tplus_usd,Т+: Основной режим (USD) - безадрес.,0,156,1,1.0,main
8,6,1,stock,Фондовый рынок и рынок депозитов,1,shares,stock_shares,Т0: Основной режим - безадрес.,0,6,0,1.0,main
9,125,1,stock,Фондовый рынок и рынок депозитов,1,shares,stock_shares_settle,Поставка по СК,0,125,1,NaN,main

durations

   interval  duration  days     title hint
0         1        60  None    минута   1м
1        10       600  None  10 минут  10м
2        60      3600  None       час   1ч
3        24     86400  None      день   1д
4         7    604800  None    неделя   1н
5        31   2678400  None     месяц   1М
6         4   8035200  None   квартал   1К

securitytypes

,id,trade_engine_id,trade_engine_name,trade_engine_title,security_type_name,security_type_title,security_group_name,stock_type
0,3,1,stock,Фондовый рынок и рынок депозитов,common_share,Акция обыкновенная,stock_shares,1
1,1,1,stock,Фондовый рынок и рынок депозитов,preferred_share,Акция привилегированная,stock_shares,2
2,51,1,stock,Фондовый рынок и рынок депозитов,depositary_receipt,Депозитарная расписка,stock_dr,D
3,54,1,stock,Фондовый рынок и рынок депозитов,ofz_bond,Государственная облигация,stock_bonds,3
4,4,1,stock,Фондовый рынок и рынок депозитов,cb_bond,Облигация центрального банка,stock_bonds,5
5,41,1,stock,Фондовый рынок и рынок депозитов,subfederal_bond,Региональная облигация,stock_bonds,4
6,45,1,stock,Фондовый рынок и рынок депозитов,municipal_bond,Муниципальная облигация,stock_bonds,C
7,2,1,stock,Фондовый рынок и рынок депозитов,corporate_bond,Корпоративная облигация,stock_bonds,6
8,43,1,stock,Фондовый рынок и рынок депозитов,exchange_bond,Биржевая облигация,stock_bonds,8
9,42,1,stock,Фондовый рынок и рынок депозитов,ifi_bond,Облигация МФО,stock_bonds,7

securitygroups

   id                  name                  title  is_hidden
0  12           stock_index                Индексы          0
1   4          stock_shares                  Акции          0
2   3           stock_bonds              Облигации          0
3   9         currency_selt                 Валюта          0
4  10         futures_forts               Фьючерсы          0
5  26       futures_options                Опционы          0
6  18              stock_dr  Депозитарные расписки          0
7  33  stock_foreign_shares       Иностранные ц.б.          0
8   6        stock_eurobond          Еврооблигации          0
9   5            stock_ppif              Паи ПИФов          0

securitycollections

,id,name,title,security_group_id
0,72,stock_index_all,Все индексы,12
1,213,stock_index_shares,Основные индексы акций,12
2,210,stock_index_shares_sectoral,Отраслевые индексы акций,12
3,249,stock_index_total_return,Индексы акций полной доходности,12
4,211,stock_index_shares_thematic,Тематические индексы акций,12
5,207,stock_index_bonds,Основные индексы облигаций,12
6,214,stock_index_bonds_state,Индексы государственных облигаций,12
7,208,stock_index_bonds_corporate,Индексы корпоративных облигаций,12
8,212,stock_index_bonds_municipal,Индексы муниципальных облигаций,12
9,209,stock_index_bonds_retiring,Индексы активов пенсионных накоплений,12

In [22]:
FULL_ID.remove(28)

In [23]:
MOEX.api_description(FULL_ID[0], True)

32: Получить таблицу инструментов по режиму торгов.
Глобальные сущности запроса: ['engine', 'market', 'board']

Возвращаемые поинтом данные:
securities: Справочник полей таблицы со статическими данными торговой сессии рынка
marketdata: Данные с текущими значениями инструментов рынка
dataversion: Версионность данных.
marketdata_yields: Доходности

Параметры запроса:
``primary_board``: Показывать инструменты - только для главного режима торгов по бумаге.
Фильтр работает только для фондового (stock) и валютного (currency) рынка.
Будьте осторожны используя данный фильтр за пределами основных режимов торгов.
Список главных режимов торгов: https://iss.moex.com/iss/securities/ колонка "primary_boardid"..
``assets``: Фильтр по коду базового актива (только для срочного рынка). Колонка ASSETCODE.
Пример: https://iss.moex.com/iss/engines/futures/markets/forts/securities?assets=EURRUBTOM,AFLT
Ограничения: не более 5 типов бумаг..
``index``: Выводить акции из базы индекса.
Только для фондового рынка..
``security_collection``: Фильтр по коллекции.
``previous_session``: Данные предыдущей сессии для forts и options рынков  . Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH (не более 10 инструментов)..
``first``: Отдать n первых строк. Значение по умолчанию: 0
``sort_column``:
``sort_order``: Значение по умолчанию: asc
``leaders``: Лидеры торгов (только для futures/options). Значение по умолчанию: 0
``nearest``: Выводить фьючерсы с ближайшей датой погашения. Значение по умолчанию: 0
``sectypes``: Фильтр по типу инструмента (только для срочного и фондового рынков).
Например:
  - https://iss.moex.com/iss/engines/futures/markets/forts/securities?sectypes=ri,gz
  - https://iss.moex.com/iss/engines/stock/markets/bonds/securities?sectypes=8
Ограничения: не более 5 типов бумаг.
!! Для срочного рынка устарело. Используйте фильтр "assets"..

Детали: http://iss.moex.com/iss/reference/32
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards/{board}/securities

In [66]:
result = MOEX.request(32, engine="futures", market="forts", board="RFUD", nearest=1,
                      assets=["MIX", "LKOH", "GLD"]
                     )
print_df(result)

securities

,SECID,BOARDID,SHORTNAME,SECNAME,PREVSETTLEPRICE,DECIMALS,MINSTEP,LASTTRADEDATE,LASTDELDATE,SECTYPE,...,HIGHLIMIT,LOWLIMIT,STEPPRICE,LASTSETTLEPRICE,PREVPRICE,IMTIME,BUYSELLFEE,SCALPERFEE,NEGOTIATEDFEE,EXERCISEFEE
0,GOM3,RFUD,GLD-6.23,Фьючерсный контракт GLD-6.23,5270.1,1,0.1,2023-06-14,2023-06-15,GO,...,5467.9,4879.1,1.0,5173.5,4969,2023-06-01 14:03:21,6.96,3.48,2.32,0.00
1,LKM3,RFUD,LKOH-6.23,Фьючерсный контракт LKOH-6.23,51796.0,0,1.0,2023-06-15,2023-06-16,LK,...,60577.0,43573.0,1.0,52075.0,51760,2023-06-01 14:03:21,10.26,5.13,3.42,0.00
2,MXM3,RFUD,MIX-6.23,Фьючерсный контракт MIX-6.23,265650.0,0,25.0,2023-06-15,2023-06-15,MX,...,285550.0,244800.0,25.0,265175.0,265550,2023-06-01 14:03:21,17.53,8.77,5.84,5.84

marketdata

,SECID,BOARDID,BID,OFFER,SPREAD,OPEN,HIGH,LOW,LAST,QUANTITY,...,NUMOFFERS,TIME,SETTLETOPREVSETTLEPRC,SEQNUM,SYSTIME,TRADEDATE,LASTTOPREVPRICE,OICHANGE,OPENPERIODPRICE,SWAPRATE
0,GOM3,RFUD,None,None,221.9,4975.1,4975.1,4975,4975,3,...,None,10:37:11,-1.33,20230601153203,2023-06-01 15:32:03,2023-06-01,0.12,-2,0.0,0.0
1,LKM3,RFUD,None,None,16.0,51749.0,52593.0,51749,52591,1,...,None,15:55:43,1.48,20230601161052,2023-06-01 16:10:52,2023-06-01,1.61,6700,0.0,0.0
2,MXM3,RFUD,None,None,25.0,265600.0,266975.0,264450,265500,3,...,None,15:55:29,-0.05,20230601161050,2023-06-01 16:10:50,2023-06-01,-0.02,1780,0.0,0.0

dataversion

   data_version          seqnum
0          7343  20230601161055

marketdata_yields

Empty DataFrame
Columns: [boardid, secid]
Index: []

In [67]:
FULL_ID.remove(32)

In [68]:
MOEX.api_description(FULL_ID[0], True)

33: Получить таблицу инструментов торговой сессии по рынку в целом.
Глобальные сущности запроса: ['engine', 'market']

Возвращаемые поинтом данные:
securities: Справочник полей таблицы со статическими данными торговой сессии рынка
marketdata: Данные с текущими значениями инструментов рынка
dataversion: Версионность данных.
marketdata_yields: Доходности

Параметры запроса:
``primary_board``: Показывать инструменты - только для главного режима торгов по бумаге.
Фильтр работает только для фондового (stock) и валютного (currency) рынка.
Будьте осторожны используя данный фильтр за пределами основных режимов торгов.
Список главных режимов торгов: https://iss.moex.com/iss/securities/ колонка "primary_boardid"..
``assets``: Фильтр по коду базового актива (только для срочного рынка). Колонка ASSETCODE.
Пример: https://iss.moex.com/iss/engines/futures/markets/forts/securities?assets=EURRUBTOM,AFLT
Ограничения: не более 5 типов бумаг..
``index``: Выводить акции из базы индекса.
Только для фондового рынка..
``security_collection``: Фильтр по коллекции.
``previous_session``: Данные предыдущей сессии для forts и options рынков  . Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH (не более 10 инструментов)..
``first``: Отдать n первых строк. Значение по умолчанию: 0
``sort_column``:
``sort_order``: Значение по умолчанию: asc
``leaders``: Лидеры торгов (только для futures/options). Значение по умолчанию: 0
``nearest``: Выводить фьючерсы с ближайшей датой погашения. Значение по умолчанию: 0
``sectypes``: Фильтр по типу инструмента (только для срочного и фондового рынков).
Например:
  - https://iss.moex.com/iss/engines/futures/markets/forts/securities?sectypes=ri,gz
  - https://iss.moex.com/iss/engines/stock/markets/bonds/securities?sectypes=8
Ограничения: не более 5 типов бумаг.
!! Для срочного рынка устарело. Используйте фильтр "assets"..

Детали: http://iss.moex.com/iss/reference/33
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/securities

In [75]:
# Аналогично
FULL_ID.remove(33)

In [76]:
MOEX.api_description(FULL_ID[0], True)

34: Получить все сделки по выбранному режиму торгов.
Глобальные сущности запроса: ['engine', 'market', 'board']

Возвращаемые поинтом данные:
trades: Перечень сделок
dataversion: Версионность данных.
trades_yields: Дополнительные доходности для сделок

Параметры запроса:
``tradeno``: Номер сделки, с которого следует начать возвращать данные.
В данных возвращаются сделки начиная с номера переданной сделки переданого в параметре tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".

Сделки возвращаются в порядке их заключения. На срочном рынке номер более поздней сделки может быть менее номера предыдущей.
. Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH.
``limit``: Количество строк в данных. Доступные значения: 1, 10, 100, 1000, 5000. Значение по умолчанию: 5000
``reversed``: обратный порядок сортировки. Значение по умолчанию: 0
``previous_session``: Сделки предыдущей сессии для forts и options рынков.
И для индексов.
. Значение по умолчанию: 0
``recno``: Только для срочного рынка (FORTS + OPTIONS).
Фильтрация по полю RECNO (в порядке заключения сделок).

Заменяет собой фильтр tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".
. Значение по умолчанию: 0
``next_trade``: Не включать текущую сделку в выдачу.. Значение по умолчанию: 0
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0
``yielddatetype``: Тип доходности. Возможные значения
- MBS
- MATDATE
- OFFERDATE.

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/34
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards/{board}/trades

In [86]:
reload_moex()

In [91]:
result = MOEX.request(34, engine="stock", market="shares", board="TQBR", 
                      tradeno=7705999026,
                      next_trade=1,
                      securities="GAZP"
                     )
print_df(result)

trades

,TRADENO,TRADETIME,BOARDID,SECID,PRICE,QUANTITY,VALUE,PERIOD,TRADETIME_GRP,SYSTIME,BUYSELL,DECIMALS,TRADINGSESSION
0,7705999272,16:22:26,TQBR,GAZP,162.04,20,32408.0,N,1622,2023-06-01 16:22:26,B,2,1
1,7705999273,16:22:26,TQBR,GAZP,162.04,80,129632.0,N,1622,2023-06-01 16:22:26,B,2,1
2,7706000704,16:22:46,TQBR,GAZP,162.04,1,1620.4,N,1622,2023-06-01 16:22:47,B,2,1
3,7706000812,16:22:49,TQBR,GAZP,162.04,29,46991.6,N,1622,2023-06-01 16:22:49,B,2,1
4,7706000813,16:22:49,TQBR,GAZP,162.04,6,9722.4,N,1622,2023-06-01 16:22:49,B,2,1
5,7706001518,16:23:00,TQBR,GAZP,162.02,1,1620.2,N,1623,2023-06-01 16:23:01,S,2,1
6,7706001519,16:23:00,TQBR,GAZP,162.01,24,38882.4,N,1623,2023-06-01 16:23:01,S,2,1
7,7706001520,16:23:00,TQBR,GAZP,162.01,1,1620.1,N,1623,2023-06-01 16:23:01,S,2,1
8,7706001521,16:23:00,TQBR,GAZP,162.01,24,38882.4,N,1623,2023-06-01 16:23:01,S,2,1
9,7706001597,16:23:01,TQBR,GAZP,162.02,2,3240.4,N,1623,2023-06-01 16:23:02,S,2,1

dataversion

   data_version          seqnum
0          7816  20230601163935

trades_yields

Empty DataFrame
Columns: [boardid, secid]
Index: []

In [93]:
FULL_ID.remove(34)

In [94]:
MOEX.api_description(FULL_ID[0], True)

35: Получить все сделки рынка.
Глобальные сущности запроса: ['engine', 'market']

Возвращаемые поинтом данные:
trades: Перечень сделок
dataversion: Версионность данных.
trades_yields: Дополнительные доходности для сделок

Параметры запроса:
``tradeno``: Номер сделки, с которого следует начать возвращать данные.
В данных возвращаются сделки начиная с номера переданной сделки переданого в параметре tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".

Сделки возвращаются в порядке их заключения. На срочном рынке номер более поздней сделки может быть менее номера предыдущей.
. Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH.
``limit``: Количество строк в данных. Доступные значения: 1, 10, 100, 1000, 5000. Значение по умолчанию: 5000
``reversed``: обратный порядок сортировки. Значение по умолчанию: 0
``previous_session``: Сделки предыдущей сессии для forts и options рынков.
И для индексов.
. Значение по умолчанию: 0
``recno``: Только для срочного рынка (FORTS + OPTIONS).
Фильтрация по полю RECNO (в порядке заключения сделок).

Заменяет собой фильтр tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".
. Значение по умолчанию: 0
``next_trade``: Не включать текущую сделку в выдачу.. Значение по умолчанию: 0
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0
``yielddatetype``: Тип доходности. Возможные значения
- MBS
- MATDATE
- OFFERDATE.

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/35
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/trades

In [96]:
# Аналогично
FULL_ID.remove(35)

In [97]:
MOEX.api_description(FULL_ID[0], True)

40: Получить доступные торговые системы.

Возвращаемые поинтом данные:
engines: Список доступных торговых систем

Детали: http://iss.moex.com/iss/reference/40
Темплейт: http://iss.moex.com/iss/engines

In [99]:
# Есть в справочнике - engines
FULL_ID.remove(40)

In [100]:
MOEX.api_description(FULL_ID[0], True)

41: Получить описание и режим работы торговой системы.
Глобальные сущности запроса: ['engine']

Возвращаемые поинтом данные:
engine: Общие атрибуты ТС
timetable:
dailytable:

Детали: http://iss.moex.com/iss/reference/41
Темплейт: http://iss.moex.com/iss/engines/{engine}

In [102]:
# Время и дни торгов, пропустим
FULL_ID.remove(41)

In [103]:
MOEX.api_description(FULL_ID[0], True)

42: Получить список рынков торговой системы.
Глобальные сущности запроса: ['engine']

Возвращаемые поинтом данные:
markets: Справочник доступных рынков и их атрибуты

Детали: http://iss.moex.com/iss/reference/42
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets

In [104]:
# Есть в справочнике
FULL_ID.remove(42)

In [105]:
MOEX.api_description(FULL_ID[0], True)

43: Получить справочник режимов торгов рынка.
Глобальные сущности запроса: ['engine', 'market']

Возвращаемые поинтом данные:
boards: Доступные режимы торгов рынка

Детали: http://iss.moex.com/iss/reference/43
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards

In [106]:
# Есть в справочнике
FULL_ID.remove(43)

In [108]:
MOEX.api_description(FULL_ID[0], True)

44: Получить описание: словарь доступных режимов торгов, описание полей публикуемых таблиц данных и т.д.
Глобальные сущности запроса: ['engine', 'market']

Возвращаемые поинтом данные:
boards: Доступные режимы торгов рынка
boardgroups: Группы режимов торгов
securities: Справочник полей таблицы со статическими данными торговой сессии рынка
marketdata: Справочник полей таблицы котировок
trades: Справочник полей таблицы сделок торговой сессии рынка
orderbook: Справочник полей таблицы с котировками (стакана заявок)
history: Справочник полей истории таблицы инструментов
trades_hist: Справочник полей таблицы сделок архив реестра сделок
marketdata_yields:
trades_yields:
history_yields:
secstats: Описание полей таблицы "Итоги для "

Детали: http://iss.moex.com/iss/reference/44
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}

In [110]:
# Возврат описания полей. Может быть полезно для анализа
result = MOEX.request(44, engine="stock", market="bonds")
print_df(result)

boards

,id,board_group_id,boardid,title,is_traded
0,122,122,AUBB,Выкуп: Аукцион - безадрес.,1
1,121,123,AUCT,Размещение: Аукцион - безадрес.,1
2,93,7,EQDB,Основной режим: Облигации Д - безадрес.,0
3,165,7,EQEO,Основной режим: Облигации (EUR) - безадрес.,0
4,37,67,EQEU,Облигации (USD) - безадрес.,0
5,228,67,EQGO,Облигации (GBP) - безадрес.,0
6,6,7,EQNB,Основной режим: Облигации внесписочные - безад...,0
7,7,7,EQNO,Основной режим: Б-Облигации - безадрес.,0
8,8,7,EQOB,Т0 Облигации - безадрес.,0
9,9,7,EQOS,Основной режим: А2-Облигации - безадрес.,0

boardgroups

,id,slug,title,is_default,is_traded
0,58,stock_bonds_tplus,Т+: Основной режим - безадрес.,1,1
1,193,stock_bonds_tplus_usd,Т+: Основной режим (USD) - безадрес.,0,1
2,68,stock_etc_tplus,Т+: Основной режим (ЕТС) - безадрес.,0,0
3,7,stock_bonds,Т0: Основной режим - безадрес.,0,0
4,105,stock_bonds_settle,Поставка по СК,0,1
5,69,stock_etc,Т0: Основной режим (ЕТС) - безадрес.,0,0
6,67,stock_bonds_euro,Т0: Основной режим (Еврооблигации) - безадрес.,0,0
7,122,stock_bonds_buyback,Выкуп - безадрес.,0,1
8,123,stock_bonds_distribution,Размещение - безадрес.,0,1
9,77,stock_bonds_darkpools,Крупные пакеты - безадрес.,0,1

securities

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,1954,SECID,Код инструмента,Идентификатор финансового инструмента,1,0,0,None,0,0,string,NaN,0
1,1920,SHORTNAME,Кратк. наим.,Краткое наименование ценной бумаги,1,0,0,None,0,0,string,NaN,1
2,1940,PREVWAPRICE,"Средневзвешенная цена предыдущего дня, % к ном...","Средневзвешенная цена предыдущего дня, % к ном...",0,0,1,None,0,0,number,NaN,0
3,1941,YIELDATPREVWAPRICE,Доходность по оценке пред. дня,Доходность по оценке пред. дня,0,0,0,None,0,0,number,NaN,0
4,1936,COUPONVALUE,Сумма купона,"Сумма купона, в валюте номинала",0,0,1,None,0,0,number,NaN,0
5,1938,NEXTCOUPON,Дата окончания купона,Дата окончания купона,0,0,1,None,0,0,date,NaN,0
6,1934,ACCRUEDINT,НКД,"НКД на дату расчетов, в валюте расчетов",0,0,0,None,0,0,number,2.0,0
7,1931,PREVPRICE,Последняя цена пред. дня,"Цена последней сделки пред. дня, % к номиналу",0,0,0,None,0,0,number,NaN,0
8,1926,LOTSIZE,Размер лота,"Размер лота, ц.б.",0,0,0,None,0,0,number,0.0,0
9,1928,FACEVALUE,Непог.долг,Непогашенный долг,0,0,0,None,0,0,number,NaN,0

marketdata

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,1954,SECID,Код инструмента,Идентификатор финансового инструмента,1,0,0,NaN,0,0,string,NaN,0
1,1956,BID,Спрос,Спрос,0,0,0,NaN,0,0,number,NaN,0
2,1957,BIDDEPTH,"Объем лучшей котировки на покупку, штук","Объем лучшей котировки на покупку, штук",0,0,0,NaN,0,0,number,0.0,0
3,1960,OFFER,Предложение,Предложение,0,0,0,NaN,0,0,number,NaN,0
4,1961,OFFERDEPTH,"Объем лучшей котировки на продажу, штук","Объем лучшей котировки на продажу, штук",0,0,0,NaN,0,0,number,0.0,0
5,2006,SPREAD,Спред,Разница между лучшей котировкой на продажу и п...,0,0,0,NaN,0,0,number,NaN,0
6,1958,BIDDEPTHT,Совокупный спрос,Совокупный спрос,0,0,0,NaN,0,0,number,0.0,0
7,1962,OFFERDEPTHT,Общий объем на продажу,"Общий объем котировок на продажу, лотов",0,0,0,NaN,0,0,number,0.0,0
8,1964,OPEN,"Первая, %","Цена первой сделки, % к номиналу",0,0,0,NaN,0,0,number,NaN,0
9,1966,LOW,"Минимум, %","Минимальная цена сделки, % к номиналу",0,0,0,NaN,0,0,number,NaN,0

trades

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,307,TRADENO,Сделка No,Номер сделки,0,0,0,None,0,0,number,0.0,0
1,308,TRADETIME,Время,"Время заключения сделки, чч:мм:сс",0,0,0,None,0,0,time,NaN,0
2,310,SECID,Код инструмента,Код инструмента,0,0,0,None,0,0,string,NaN,0
3,311,PRICE,Цена,"Цена, в валюте расчетов",0,0,0,None,0,0,number,NaN,0
4,312,QUANTITY,"Объем, лотов","Объем сделки, лотов",0,0,0,None,0,0,number,0.0,0
5,314,PERIOD,Период,"Период торговой сессии, когда была заключена с...",0,0,0,None,0,0,string,NaN,0
6,313,VALUE,Объем сделки,"Объем сделки, в валюте расчетов",0,0,0,None,0,0,number,NaN,0
7,315,YIELD,Доходность сделки,"Доходность сделки, % годовых",0,0,0,None,0,0,number,NaN,0
8,309,BOARDID,Код режима торгов,Код режима торгов,0,0,1,None,0,0,string,NaN,0
9,3178,SYSTIME,Время загрузки,Время загрузки данных системой,0,1,1,None,0,0,date,NaN,0

orderbook

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,155,SECID,Код инструмента,Код инструмента,0,0,1,None,0,0,string,NaN,0
1,154,BOARDID,Код режима торгов,Режим торгов,0,0,1,None,0,0,string,NaN,0
2,156,BUYSELL,К/П,"Направленность заявки, приведшая к заключению ...",0,0,0,None,0,0,string,NaN,0
3,157,PRICE,Цена,Цена котировки,0,0,0,None,0,0,number,NaN,0
4,158,QUANTITY,"Объем котировки, лотов","Объем котировки, лотов",0,0,0,None,0,0,number,NaN,0
5,159,YIELD,Доходность,Доходность,0,0,0,None,0,0,number,NaN,0
6,160,UPDATETIME,Время,Время последнего обновления,0,1,1,None,0,0,time,NaN,0
7,161,SEQNUM,номер обновления (служебное поле),номер обновления (служебное поле),0,1,1,None,0,0,number,0.0,0
8,3150,SYSTIME,Время загрузки,Время загрузки данных системой,0,1,1,None,0,0,date,NaN,0

history

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,2745,TRADEDATE,Дата торгов,Дата торгов,1,0,0,NaN,0,0,date,NaN,0
1,2746,SECID,Код инструмента,Идентификатор финансового инструмента,0,0,0,NaN,0,0,string,NaN,0
2,855,BOARDNAME,Режим торгов,Режим торгов,1,0,0,NaN,0,0,string,NaN,0
3,2743,BOARDID,Код режима,Идентификатор режима торгов,0,0,0,NaN,0,0,string,NaN,0
4,850,SHORTNAME,Кратк. наим.,Краткое наименование,1,0,0,NaN,0,0,string,NaN,1
5,853,REGNUMBER,Код гос. регистрации,Код гос. регистрации,1,0,0,NaN,0,0,string,NaN,0
6,3314,ISIN,Код ISIN,Код ISIN,1,0,0,NaN,0,0,string,NaN,0
7,3316,MATDATE,Дата погашения,Дата погашения,1,0,0,NaN,0,0,date,NaN,0
8,3313,LISTNAME,Уровень листинга,Уровень листинга,0,0,0,NaN,0,0,string,NaN,0
9,2744,FACEVALUE,Непог.долг,Непогашенный долг,0,0,0,NaN,0,0,number,NaN,0

trades_hist

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,3106,TRADENO,Номер сделки,Номер сделки,0,0,0,None,0,0,number,NaN,0
1,3099,TRADEDATE,Дата торгов,Дата торгов,0,0,0,None,0,0,date,NaN,0
2,3104,TRADETIME,Время,Время заключения сделки,0,0,0,None,0,0,time,NaN,0
3,3098,SECID,Инструмент,Идентификатор финансового инструмента,0,0,0,None,0,0,string,NaN,0
4,3100,BOARDID,Режим торгов,Идентификатор режима торгов,0,0,0,None,0,0,string,NaN,0
5,3101,PRICE,Цена сделки,"Цена сделки, % к номиналу",0,0,0,None,0,0,number,NaN,0
6,3107,QUANTITY,"Объем, шт.","Объем сделки, штук",0,0,0,None,0,0,number,NaN,0
7,3102,VALUE,"Объем, руб.","Объем сделки, рублей",0,0,0,None,0,0,number,NaN,0
8,3105,YIELD,Доходность сделки,"Доходность сделки, % годовых",0,0,0,None,0,0,number,NaN,0
9,3103,ACCINT,НКД,"Накопленный купонный доход (НКД), по одной цен...",0,0,0,None,0,0,number,NaN,0

marketdata_yields

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,6153,SECID,Код инструмента,Код инструмента,0,0,0,None,0,0,string,NaN,0
1,6155,BOARDID,Код режима,Идентификатор режима торгов,0,0,0,None,0,0,string,NaN,0
2,6157,PRICE,Цена,Цена по которой была рассчитана доходность,0,0,0,None,0,0,number,NaN,0
3,6159,YIELDDATE,"Дата, к кот.рассч.дох.","Дата, к которой рассчитывается доходность",0,0,0,None,0,0,date,NaN,0
4,6161,ZCYCMOMENT,Маркер КБД,Дата-временной маркер использованной в расчета...,0,0,0,None,0,0,datetime,NaN,0
5,6163,YIELDDATETYPE,"Тип даты, к кот. расч. пар.","Тип даты, к которой рассчитывается доходность ...",0,0,0,None,0,0,string,NaN,0
6,6165,EFFECTIVEYIELD,Эффективная доходность,Эффективная доходность,0,0,0,None,0,0,number,4.0,0
7,6167,DURATION,Дюрация,"Дюрация, дней",0,0,0,None,0,0,number,0.0,0
8,6169,ZSPREADBP,Z-spread,Z-spread,0,0,0,None,0,0,number,0.0,0
9,6171,GSPREADBP,G-spread,G-spread,0,0,0,None,0,0,number,0.0,0

trades_yields

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,6133,TRADENO,Сделка No,Номер сделки,0,0,0,None,0,0,number,0.0,0
1,6135,SECID,Код инструмента,Код инструмента,0,0,0,None,0,0,string,NaN,0
2,6137,BOARDID,Код режима,Идентификатор режима торгов,0,0,0,None,0,0,string,NaN,0
3,6139,ZCYCMOMENT,Маркер КБД,Дата-временной маркер использованной в расчета...,0,0,0,None,0,0,datetime,NaN,0
4,6141,YIELDDATETYPE,"Тип даты, к кот. расч. пар.","Тип даты, к которой рассчитывается доходность ...",0,0,0,None,0,0,string,NaN,0
5,6143,EFFECTIVEYIELD,Эффективная доходность,Эффективная доходность,0,0,0,None,0,0,number,4.0,0
6,6145,DURATION,Дюрация,"Дюрация, дней",0,0,0,None,0,0,number,0.0,0
7,6147,ZSPREADBP,Z-spread,Z-spread,0,0,0,None,0,0,number,0.0,0
8,6149,GSPREADBP,G-spread,G-spread,0,0,0,None,0,0,number,0.0,0
9,6151,SYSTIME,Время загрузки,Время загрузки данных системой (служебное поле),0,0,0,None,0,0,datetime,NaN,0

history_yields

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,6325,TRADEDATE,Дата,Дата торгов,0,0,0,None,0,0,date,NaN,0
1,6327,SECID,Код инструмента,Код инструмента,0,0,0,None,0,0,string,NaN,0
2,6329,BOARDID,Код режима,Идентификатор режима торгов,0,0,0,None,0,0,string,NaN,0
3,6331,YIELDDATE,"Дата, к кот.рассч.дох.","Дата, к которой рассчитывается доходность",0,0,0,None,0,0,date,NaN,0
4,6333,YIELDDATETYPE,"Тип даты, к кот. расч. пар.","Тип даты, к которой рассчитывается доходность ...",0,0,0,None,0,0,string,NaN,0
5,6335,PRICE,Цена,Цена по которой была рассчитана доходность,0,0,0,None,0,0,number,NaN,0
6,6337,ACCINT,НКД,"НКД на дату расчетов, в валюте расчетов",0,0,0,None,0,0,number,2.0,0
7,6339,ZCYCMOMENT,Маркер КБД,Дата-временной маркер использованной в расчета...,0,0,0,None,0,0,datetime,NaN,0
8,6341,EFFECTIVEYIELD,Эффективная доходность,Эффективная доходность,0,0,0,None,0,0,number,4.0,0
9,6343,DURATION,Дюрация,"Дюрация, дней",0,0,0,None,0,0,number,0.0,0

secstats

,id,name,short_title,title,is_ordered,is_system,is_hidden,trend_by,is_signed,has_percent,type,precision,is_linked
0,6515,SECID,Код инструмента,Идентификатор финансового инструмента,0,0,0,None,0,0,string,NaN,0
1,6517,BOARDID,Код режима,Идентификатор режима торгов,0,0,0,None,0,0,string,NaN,0
2,6519,TRADINGSESSION,Торговая сессия,Торговая сессия,0,0,0,None,0,0,string,NaN,0
3,6521,TIME,Время последней,Время последней сделки,0,0,0,None,0,0,time,NaN,0
4,6523,PRICEMINUSPREVWAPRICE,К оценке пред. дня,Цена последней сделки к оценке предыдущего дня,0,0,0,None,0,0,number,NaN,0
5,6525,VOLTODAY,Объем в бумагах,Объем заключенных сделок в единицах ценных бум...,0,0,0,None,0,0,number,0.0,0
6,6527,VALTODAY,Объем,"Объем совершенных сделок, в валюте расчетов",0,0,0,None,0,0,number,0.0,0
7,6529,HIGHBID,Наибольшая цена спроса,Наибольшая цена спроса в течение торговой сессии,0,0,0,None,0,0,number,NaN,0
8,6531,LOWOFFER,Наименьшая цена предложения,Наименьшая цена предложения в течение торговой...,0,0,0,None,0,0,number,NaN,0
9,6533,LASTOFFER,Предложение сессии,Лучшая котировка на продажу на момент завершен...,0,0,0,None,0,0,number,NaN,0

In [111]:
FULL_ID.remove(44)

In [112]:
MOEX.api_description(FULL_ID[0], True)

45: Получить справочник групп режимов торгов.
Глобальные сущности запроса: ['engine', 'market']

Возвращаемые поинтом данные:
boardgroups: Группы режимов торгов

Детали: http://iss.moex.com/iss/reference/45
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boardgroups

In [113]:
# Есть в справочнике
FULL_ID.remove(45)

In [114]:
MOEX.api_description(FULL_ID[0], True)

46: Получить свечи указанного инструмента по выбранному режиму торгов.
Глобальные сущности запроса: ['engine', 'market', 'board', 'security']

Возвращаемые поинтом данные:
candles: Свечи в формате HLOCV

Параметры запроса:
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0
``till``: Дата, до которой выводить данные.
Формат: ГГГГ-ММ-ДД.. Значение по умолчанию: 2037-12-31
``from``: Дата, начиная с которой необходимо начать выводить данные.
Формат: ГГГГ-ММ-ДД..
``interval``: Интервал графика.. Значение по умолчанию: 10
``iss.reverse``: Изменить порядок сортировки на обратный. Принимает значения true/false.. Значение по умолчанию: false

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/46
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards/{board}/securities/{security}/candles

In [130]:
# Свечи: уже исторические данные
result = MOEX.request(46, engine="stock", market="shares", board="TQBR", security="GMKN", interval=24,
                      _from="2023-01-01", 
                      iss__reverse=True
                     )
print_df(result)

,open,close,high,low,value,volume,begin,end
0,14620,14568,14638,14480,486325732,33419,2023-06-01 00:00:00,2023-06-01 17:38:29
1,14538,14580,14588,14400,762081178,52560,2023-05-31 00:00:00,2023-05-31 23:59:59
2,14586,14574,14750,14526,939759858,64190,2023-05-30 00:00:00,2023-05-30 23:59:59
3,14684,14654,14796,14562,976281166,66642,2023-05-29 00:00:00,2023-05-29 23:59:59
4,14562,14670,14728,14552,774999220,52811,2023-05-26 00:00:00,2023-05-26 23:59:59
5,14736,14562,14736,14550,709017862,48575,2023-05-25 00:00:00,2023-05-25 23:59:59
6,14640,14696,14758,14564,786615576,53631,2023-05-24 00:00:00,2023-05-24 23:59:59
7,14620,14648,14684,14526,811575002,55576,2023-05-23 00:00:00,2023-05-23 23:59:59
8,14740,14602,14784,14580,566582616,38625,2023-05-22 00:00:00,2023-05-22 23:59:59
9,14694,14730,14740,14520,1065736826,72821,2023-05-19 00:00:00,2023-05-19 23:59:59

In [131]:
FULL_ID.remove(46)

In [132]:
MOEX.api_description(FULL_ID[0], True)

48: Получить период дат рассчитанных свечей.
Глобальные сущности запроса: ['engine', 'market', 'board', 'security']

Возвращаемые поинтом данные:
borders:
durations: Справочник доступных расчетных интервалов свечей в формате HLOCV

Детали: http://iss.moex.com/iss/reference/48
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards/{board}/securities/{security}/candleborders

In [134]:
# Может быть полезно, для чека доступных свечек
result = MOEX.request(48, engine="stock", market="shares", board="TQBR", security="GMKN", blocks=["borders"])
print_df(result)

                 begin                  end  interval
0  2014-06-09 10:00:00  2023-06-01 17:59:59         1
1  2010-04-01 00:00:00  2023-06-01 00:00:00         4
2  2010-04-26 00:00:00  2023-06-01 00:00:00         7
3  2014-06-09 10:00:00  2023-06-01 17:41:08        10
4  2010-04-28 00:00:00  2023-06-01 17:41:09        24
5  2010-04-01 00:00:00  2023-06-01 00:00:00        31
6  2014-06-09 10:00:00  2023-06-01 17:41:08        60

In [135]:
FULL_ID.remove(48)

In [136]:
MOEX.api_description(FULL_ID[0], True)

49: Получить описание режима торгов.
Глобальные сущности запроса: ['engine', 'market', 'board']

Возвращаемые поинтом данные:
board: Описание режима торгов

Детали: http://iss.moex.com/iss/reference/49
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards/{board}

In [138]:
# Есть в справочнике
FULL_ID.remove(49)

In [139]:
MOEX.api_description(FULL_ID[0], True)

50: Получить описание группы режимов торгов.
Глобальные сущности запроса: ['engine', 'market', 'boardgroup']

Возвращаемые поинтом данные:
boardgroup: Описание группы режимов торгов

Детали: http://iss.moex.com/iss/reference/50
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boardgroups/{boardgroup}

In [140]:
# Есть в справочнике
FULL_ID.remove(50)

In [141]:
MOEX.api_description(FULL_ID[0], True)

52: Получить данные по конкретному инструменту рынка.
Глобальные сущности запроса: ['engine', 'market', 'security']

Возвращаемые поинтом данные:
securities: Справочник полей таблицы со статическими данными торговой сессии рынка
marketdata: Данные с текущими значениями инструментов рынка
dataversion: Версионность данных.
marketdata_yields: Доходности

Параметры запроса:
``primary_board``: Показывать инструменты - только для главного режима торгов по бумаге.
Фильтр работает только для фондового (stock) и валютного (currency) рынка.
Будьте осторожны используя данный фильтр за пределами основных режимов торгов.
Список главных режимов торгов: https://iss.moex.com/iss/securities/ колонка "primary_boardid"..
``assets``: Фильтр по коду базового актива (только для срочного рынка). Колонка ASSETCODE.
Пример: https://iss.moex.com/iss/engines/futures/markets/forts/securities?assets=EURRUBTOM,AFLT
Ограничения: не более 5 типов бумаг..
``index``: Выводить акции из базы индекса.
Только для фондового рынка..
``security_collection``: Фильтр по коллекции.
``previous_session``: Данные предыдущей сессии для forts и options рынков  . Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH (не более 10 инструментов)..
``first``: Отдать n первых строк. Значение по умолчанию: 0
``sort_column``:
``sort_order``: Значение по умолчанию: asc
``leaders``: Лидеры торгов (только для futures/options). Значение по умолчанию: 0
``nearest``: Выводить фьючерсы с ближайшей датой погашения. Значение по умолчанию: 0
``sectypes``: Фильтр по типу инструмента (только для срочного и фондового рынков).
Например:
  - https://iss.moex.com/iss/engines/futures/markets/forts/securities?sectypes=ri,gz
  - https://iss.moex.com/iss/engines/stock/markets/bonds/securities?sectypes=8
Ограничения: не более 5 типов бумаг.
!! Для срочного рынка устарело. Используйте фильтр "assets"..

Детали: http://iss.moex.com/iss/reference/52
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/securities/{security}

In [142]:
# Аналог id=34
FULL_ID.remove(52)

In [143]:
MOEX.api_description(FULL_ID[0], True)

53: Получить данные по указанному инструменту на выбранном режиме торгов.
Глобальные сущности запроса: ['engine', 'market', 'board', 'security']

Возвращаемые поинтом данные:
securities: Справочник полей таблицы со статическими данными торговой сессии рынка
marketdata: Данные с текущими значениями инструментов рынка
dataversion: Версионность данных.
marketdata_yields: Доходности

Параметры запроса:
``primary_board``: Показывать инструменты - только для главного режима торгов по бумаге.
Фильтр работает только для фондового (stock) и валютного (currency) рынка.
Будьте осторожны используя данный фильтр за пределами основных режимов торгов.
Список главных режимов торгов: https://iss.moex.com/iss/securities/ колонка "primary_boardid"..
``assets``: Фильтр по коду базового актива (только для срочного рынка). Колонка ASSETCODE.
Пример: https://iss.moex.com/iss/engines/futures/markets/forts/securities?assets=EURRUBTOM,AFLT
Ограничения: не более 5 типов бумаг..
``index``: Выводить акции из базы индекса.
Только для фондового рынка..
``security_collection``: Фильтр по коллекции.
``previous_session``: Данные предыдущей сессии для forts и options рынков  . Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH (не более 10 инструментов)..
``first``: Отдать n первых строк. Значение по умолчанию: 0
``sort_column``:
``sort_order``: Значение по умолчанию: asc
``leaders``: Лидеры торгов (только для futures/options). Значение по умолчанию: 0
``nearest``: Выводить фьючерсы с ближайшей датой погашения. Значение по умолчанию: 0
``sectypes``: Фильтр по типу инструмента (только для срочного и фондового рынков).
Например:
  - https://iss.moex.com/iss/engines/futures/markets/forts/securities?sectypes=ri,gz
  - https://iss.moex.com/iss/engines/stock/markets/bonds/securities?sectypes=8
Ограничения: не более 5 типов бумаг.
!! Для срочного рынка устарело. Используйте фильтр "assets"..

Детали: http://iss.moex.com/iss/reference/53
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards/{board}/securities/{security}

In [144]:
# Аналог id=33
FULL_ID.remove(53)

In [145]:
MOEX.api_description(FULL_ID[0], True)

55: Получить сделки по инструменту.
Глобальные сущности запроса: ['engine', 'market', 'security']

Возвращаемые поинтом данные:
trades: Перечень сделок
dataversion: Версионность данных.
trades_yields: Дополнительные доходности для сделок

Параметры запроса:
``tradeno``: Номер сделки, с которого следует начать возвращать данные.
В данных возвращаются сделки начиная с номера переданной сделки переданого в параметре tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".

Сделки возвращаются в порядке их заключения. На срочном рынке номер более поздней сделки может быть менее номера предыдущей.
. Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH.
``limit``: Количество строк в данных. Доступные значения: 1, 10, 100, 1000, 5000. Значение по умолчанию: 5000
``reversed``: обратный порядок сортировки. Значение по умолчанию: 0
``previous_session``: Сделки предыдущей сессии для forts и options рынков.
И для индексов.
. Значение по умолчанию: 0
``recno``: Только для срочного рынка (FORTS + OPTIONS).
Фильтрация по полю RECNO (в порядке заключения сделок).

Заменяет собой фильтр tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".
. Значение по умолчанию: 0
``next_trade``: Не включать текущую сделку в выдачу.. Значение по умолчанию: 0
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0
``yielddatetype``: Тип доходности. Возможные значения
- MBS
- MATDATE
- OFFERDATE.

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/55
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/securities/{security}/trades

In [146]:
# Аналог id=35
FULL_ID.remove(55)

In [147]:
MOEX.api_description(FULL_ID[0], True)

56: Получить все сделки указанного инструмента по выбранному режиму торгов.
Глобальные сущности запроса: ['engine', 'market', 'board', 'security']

Возвращаемые поинтом данные:
trades: Перечень сделок
dataversion: Версионность данных.
trades_yields: Дополнительные доходности для сделок

Параметры запроса:
``tradeno``: Номер сделки, с которого следует начать возвращать данные.
В данных возвращаются сделки начиная с номера переданной сделки переданого в параметре tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".

Сделки возвращаются в порядке их заключения. На срочном рынке номер более поздней сделки может быть менее номера предыдущей.
. Значение по умолчанию: 0
``securities``: Фильтр-список инструментов. Получение данных производится только по инстурментам из списка securities. Например: securities=GAZP,AFLT,LKOH.
``limit``: Количество строк в данных. Доступные значения: 1, 10, 100, 1000, 5000. Значение по умолчанию: 5000
``reversed``: обратный порядок сортировки. Значение по умолчанию: 0
``previous_session``: Сделки предыдущей сессии для forts и options рынков.
И для индексов.
. Значение по умолчанию: 0
``recno``: Только для срочного рынка (FORTS + OPTIONS).
Фильтрация по полю RECNO (в порядке заключения сделок).

Заменяет собой фильтр tradeno.
Если необходимо начать со следующей сделки - используйте параметр "next_trade=1".
. Значение по умолчанию: 0
``next_trade``: Не включать текущую сделку в выдачу.. Значение по умолчанию: 0
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0
``yielddatetype``: Тип доходности. Возможные значения
- MBS
- MATDATE
- OFFERDATE.

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/56
Темплейт: http://iss.moex.com/iss/engines/{engine}/markets/{market}/boards/{board}/securities/{security}/trades

In [182]:
result = MOEX.request(65, engine="stock", market="shares", security="ARSA",  board="TQBR",
                      _from="2023-05-01", tradingsession=3
                     )
print_df(result)

,BOARDID,TRADEDATE,SHORTNAME,SECID,NUMTRADES,VALUE,OPEN,LOW,HIGH,LEGALCLOSEPRICE,...,MARKETPRICE2,MARKETPRICE3,ADMITTEDQUOTE,MP2VALTRD,MARKETPRICE3TRADESVALUE,ADMITTEDVALUE,WAVAL,TRADINGSESSION,CURRENCYID,TRENDCLSPR
0,TQBR,2023-05-02,Арсагера,ARSA,4942,27666540,6.21,6.00,7.50,6.25,...,6.70,6.70,None,27666540,27666540,None,0,3,SUR,1.63
1,TQBR,2023-05-03,Арсагера,ARSA,547,2873740,6.53,6.00,6.53,6.18,...,6.20,6.20,None,2873740,2873740,None,0,3,SUR,-0.48
2,TQBR,2023-05-04,Арсагера,ARSA,2579,13574929,6.18,6.03,7.44,6.50,...,6.68,6.68,None,13574929,13574929,None,0,3,SUR,4.50
3,TQBR,2023-05-05,Арсагера,ARSA,486,2685128,6.54,6.20,6.55,6.28,...,6.31,6.31,None,2685128,2685128,None,0,3,SUR,-3.38
4,TQBR,2023-05-08,Арсагера,ARSA,345,1645173,6.28,6.21,6.70,6.41,...,6.38,6.38,None,1645173,1645173,None,0,3,SUR,1.59
5,TQBR,2023-05-10,Арсагера,ARSA,370,2039270,6.38,6.30,6.54,6.41,...,6.41,6.41,None,2039270,2039270,None,0,3,SUR,0.16
6,TQBR,2023-05-11,Арсагера,ARSA,514,2722085,6.45,6.39,6.89,6.54,...,6.60,6.60,None,2722085,2722085,None,0,3,SUR,2.35
7,TQBR,2023-05-12,Арсагера,ARSA,239,966852,6.54,6.45,6.68,6.52,...,6.52,6.52,None,966852,966852,None,0,3,SUR,0.00
8,TQBR,2023-05-15,Арсагера,ARSA,225,1425937,6.60,6.44,6.70,6.60,...,6.54,6.54,None,1425937,1425937,None,0,3,SUR,1.22
9,TQBR,2023-05-16,Арсагера,ARSA,2556,14699273,6.63,6.63,7.88,6.94,...,7.23,7.23,None,14699273,14699273,None,0,3,SUR,4.83

In [161]:
MOEX.api_description(649, True)

649: Текущие цены бумаг

Возвращаемые поинтом данные:
currentprices: Текущие цены фондового рынка
currentprices.dates:

Параметры запроса:
``date``: Значение по умолчанию: today
``start``: Значение по умолчанию: 0
``tradingsession``: Фильтровать по типу торговой сессии:
  1 - Утренняя сессия
  1 - Основная сессия
  2 - Вечерняя сессия
  3 - Суммарно по всем сессиям
По умолчанию показываются все сессии..

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/649
Темплейт: http://iss.moex.com/iss/statistics/engines/stock/currentprices

In [164]:
print_df(MOEX.request(649, date="2023-05-19"))

currentprices

C:\projects/moex_research\api_lib\main.py:318: UserWarning: К API стучались 100 раз. Возвращены не все данные!!!
  warnings.warn(f"К API стучались {cnt} раз. Возвращены не все данные!!!")

,TRADEDATE,BOARDID,SECID,TRADETIME,CURPRICE,LASTPRICE,LEGALCLOSE,TRADINGSESSION
0,2023-05-19,FQBR,A-RM,17:40:00,10427.0,0.0,10427.0,1
1,2023-05-19,FQBR,AA-RM,17:40:00,5182.0,0.0,5182.0,1
2,2023-05-19,FQBR,AAL-RM,17:40:00,1200.0,0.0,1200.0,1
3,2023-05-19,FQBR,AAP-RM,17:40:00,16751.0,0.0,16751.0,1
4,2023-05-19,FQBR,AAPL-RM,17:40:00,11984.0,0.0,11984.0,1
5,2023-05-19,FQBR,ABBV-RM,17:40:00,9705.0,0.0,9705.0,1
6,2023-05-19,FQBR,ABC-RM,17:40:00,11156.0,0.0,11156.0,1
7,2023-05-19,FQBR,ABNB-RM,17:40:00,12200.0,0.0,12200.0,1
8,2023-05-19,FQBR,ABT-RM,17:40:00,10000.0,0.0,10000.0,1
9,2023-05-19,FQBR,ACAD-RM,17:40:00,1300.0,0.0,1300.0,1

currentprices.dates

         from        till
0  2009-09-01  2023-05-31

In [191]:
MOEX.api_description(881, True)

881: Доска опционов
Глобальные сущности запроса: ['asset']

Возвращаемые поинтом данные:
call: Список CALL опционов
put:
asset: Базовый актив - справочная информация

Параметры запроса:
``expiration_date``: Дата исполнения контракта.

Детали: http://iss.moex.com/iss/reference/881
Темплейт: http://iss.moex.com/iss/statistics/engines/futures/markets/options/assets/{asset}/optionboard

In [192]:
print_df(MOEX.request(881, asset="GAZP"))

call

,SECID,BOARDID,STRIKE,THEORPRICE,VOLAT,LAST,BID,OFFER,VOLTODAY,OPENPOSITION
0,GZ85CF3B,ROPD,85.0,77.31,130.56676,NaN,0.02,NaN,NaN,NaN
1,GZ90CF3B,ROPD,90.0,72.32,130.03175,NaN,0.02,NaN,NaN,NaN
2,GZ95CF3B,ROPD,95.0,67.32,128.97380,NaN,0.02,NaN,NaN,NaN
3,GZ100CF3B,ROPD,100.0,62.34,127.04037,NaN,0.02,NaN,NaN,NaN
4,GZ105CF3B,ROPD,105.0,57.35,123.82407,NaN,0.02,NaN,NaN,NaN
5,GZ110CF3B,ROPD,110.0,52.37,118.95440,NaN,0.02,NaN,NaN,NaN
6,GZ115CF3B,ROPD,115.0,47.40,112.21195,NaN,0.02,NaN,NaN,NaN
7,GZ120CF3B,ROPD,120.0,42.42,103.62689,NaN,0.02,NaN,NaN,NaN
8,GZ125CF3B,ROPD,125.0,37.45,93.52507,NaN,0.02,NaN,NaN,NaN
9,GZ130CF3B,ROPD,130.0,32.46,82.50258,NaN,0.02,NaN,NaN,NaN

put

,SECID,BOARDID,STRIKE,THEORPRICE,VOLAT,LAST,BID,OFFER,VOLTODAY,OPENPOSITION
0,GZ85CR3B,ROPD,85.0,0.01,130.56676,NaN,NaN,4.6,NaN,NaN
1,GZ90CR3B,ROPD,90.0,0.01,130.03175,NaN,NaN,4.6,NaN,NaN
2,GZ95CR3B,ROPD,95.0,0.01,128.97380,NaN,NaN,4.6,NaN,NaN
3,GZ100CR3B,ROPD,100.0,0.01,127.04037,NaN,NaN,4.6,NaN,NaN
4,GZ105CR3B,ROPD,105.0,0.02,123.82407,NaN,NaN,4.6,NaN,NaN
5,GZ110CR3B,ROPD,110.0,0.03,118.95440,NaN,NaN,4.6,NaN,NaN
6,GZ115CR3B,ROPD,115.0,0.05,112.21195,NaN,NaN,4.6,NaN,NaN
7,GZ120CR3B,ROPD,120.0,0.07,103.62689,NaN,NaN,4.6,NaN,NaN
8,GZ125CR3B,ROPD,125.0,0.09,93.52507,NaN,NaN,4.6,NaN,NaN
9,GZ130CR3B,ROPD,130.0,0.10,82.50258,NaN,NaN,4.6,NaN,NaN

asset

,CENTRALSTRIKE,UNDERLYINGASSET,UNDERLYINGTYPE,UNDERLYINGSETTLEPRICE,LASTDELDATE
0,160.0,GAZP,S,162.2,2023-06-07

In [193]:
MOEX.api_description(883, True)

883: Открытые позиции по опционной серии
Глобальные сущности запроса: ['asset']

Возвращаемые поинтом данные:
open_positions: Количество открытых позиций

Параметры запроса:
``date``: Значение по умолчанию: today
``asset_type``: Фильтр по типу базового актива. (S - Опционы на акцию, F - Опционы на фьючерс). Значение по умолчанию: S
``option_type``: Тип опциона: 'C' - Call, 'P' - Put.. Значение по умолчанию: C

Детали: http://iss.moex.com/iss/reference/883
Темплейт: http://iss.moex.com/iss/statistics/engines/futures/markets/options/assets/{asset}/openpositions

In [195]:
print_df(MOEX.request(883, asset="GAZP"))

,tradedate,asset,option_asset_type,option_type,is_fiz,persons_long,persons_short,open_position_long,open_position_short,oichange_long,oichange_short
0,2023-05-31,GAZP,S,C,0,2,645,821426,821187,42457,42812
1,2023-05-31,GAZP,S,C,1,16,162,21283,21522,-13067,-13422

In [196]:
MOEX.api_description(767, True)

767: Сводная статистика по клиентам с самым высоким нетто-потоком. Детали https://fs.moex.com/f/10374/netflow2-demo-en.html

Возвращаемые поинтом данные:
netflow2:

Параметры запроса:
``date``: Значение по умолчанию: today

Детали: http://iss.moex.com/iss/reference/767
Темплейт: http://iss.moex.com/iss/analyticalproducts/netflow2/securities

In [197]:
print_df(MOEX.request(767, date="2023-05-04"))

,date,ticker,p30,p70,p100,pv30,pv70,pv100,vol,oi
0,2023-05-04,AFKS,1503100,645900,447100,22891413,10056862,7043610,71439800,28767400
1,2023-05-04,AFLT,-1536770,-979340,-882440,-57210638,-36260908,-32764835,89004900,30517320
2,2023-05-04,ALRS,-164700,-151290,-92380,-10762463,-9866247,-5991695,8856840,4809000
3,2023-05-04,EUR,-34247000,-21844000,-17952000,-2969962297,-1892728157,-1553997207,1289750000,383506000
4,2023-05-04,EUR_RUB__TOD,-18286000,-10451000,-6990000,-1591792700,-909671615,-608391005,308260000,176446000
5,2023-05-04,EUR_RUB__TOM,-11070000,-6467000,-4728000,-955205480,-555263467,-404736415,981490000,292164000
6,2023-05-04,FEES,-88170000,-129110000,-106930000,-9237752,-13621796,-11298217,2900240000,1324620000
7,2023-05-04,FIVE,-5062,-8251,-8018,-7270057,-11852260,-11513574,135288,85808
8,2023-05-04,GAZP,-14130,27670,113720,-2409852,4682941,19684006,32412660,16074020
9,2023-05-04,GMKN,-5181,-5883,-5524,-75001760,-85152486,-79938672,117752,66732

In [198]:
MOEX.api_description(169, True)

169: Средневзвешенные ставки по операциям центрального банка

Возвращаемые поинтом данные:
date:
dates:

Параметры запроса:
``date``: Дата за которую необходимо вывести данные.
Формат: ГГГГ-ММ-ДД.. Значение по умолчанию: today

Детали: http://iss.moex.com/iss/reference/169
Темплейт: http://iss.moex.com/iss/statistics/engines/state/markets/repo/cboper

In [200]:
# Старье
print_df(MOEX.request(169))

date

,DAYS,TRADEDATE,WADEPSRATE,WAREPORATE,WAREPORATEFIXN,TITLE,DECIMALS
0,1_DAY,12/10,4.25,None,None,1 день *,2
1,1_WEEK,12/10,4.00,None,None,1 неделя **,2
2,1_YEAR,12/10,NaN,None,None,1 год,2
3,3_MONTHS,12/10,0.00,None,None,3 месяца,2
4,4_WEEKS,12/10,0.00,None,None,4 недели,2
5,6_MONTHS,12/10,NaN,None,None,6 месяцев,2

dates

         FROM        TILL
0  2005-06-21  2012-10-12

In [201]:
MOEX.api_description(172, True)

172: Коэффициенты корелляции фондового рынка

Возвращаемые поинтом данные:
coefficients: Коэффициенты корелляции фондового рынка
coefficients.cursor:
coefficients.dates:

Параметры запроса:
``date``: Дата за которую необходимо вывести данные. Формат: ГГГГ-ММ-ДД.. Значение по умолчанию: today
``start``: Значение по умолчанию: 0

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/172
Темплейт: http://iss.moex.com/iss/statistics/engines/stock/markets/shares/correlations

In [205]:
print_df(MOEX.request(172, date="2023-05-04"))

coefficients

C:\projects/moex_research\api_lib\main.py:281: UserWarning: К API стучались 100 раз. Возвращены не все данные!!!
  warnings.warn(f"К API стучались {cnt} раз. Возвращены не все данные!!!")

  SECID  FXSECID   TRADEDATE  COEFF_CORRELATION  COEFF_BETA
0  ABRD     GAZP  2023-05-04             0.2735      0.7723
1  ABRD     GMKN  2023-05-04             0.4225      1.2850
2  ABRD     IDVP  2023-05-04            -0.1188     -0.1748
3  ABRD    IMOEX  2023-05-04             0.4124      1.5329
4  ABRD   IMOEX2  2023-05-04             0.3267      1.0955
5  ABRD     LKOH  2023-05-04             0.2658      0.6815
6  ABRD   MOEX10  2023-05-04             0.4373      1.6089
7  ABRD   MOEXBC  2023-05-04             0.3938      1.4519
8  ABRD  MOEXBMI  2023-05-04             0.4220      1.5748
9  ABRD   MOEXCH  2023-05-04             0.3483      1.2509

coefficients.dates

         from        till
0  2010-02-27  2023-05-31

In [208]:
MOEX.api_description(843, True)

843: RUSFAR расшифровка показателей

Возвращаемые поинтом данные:
analytics.columns:
analytics:
analytics.dates:

Параметры запроса:
``date``: дата за которую необходимо отобразить данные.
По умолчанию за последнюю дату в итогах торгов.. Значение по умолчанию: today

Детали: http://iss.moex.com/iss/reference/843
Темплейт: http://iss.moex.com/iss/statistics/engines/stock/markets/index/rusfar

In [209]:
print_df(MOEX.request(843))

analytics.columns

,Column,Russian,English
0,tradedate,Дата расчета,Calculation date
1,secid,Код инструмента,Instrument ID
2,Numtrades,Количество сделок,Trades count
3,AvgTradesVol,Средний объем сделок,Average trades volume
4,MinTradePrice,Минимальная цена сделок,Min deal price
5,MaxTradePrice,Максимальная цена сделок,Max deal price
6,Vol,Объем сделок,Trades volume
7,minVol,"Мин.объем сделок, необходимый для учета заявок...","Min trades volume, required for orders count f..."
8,VolShare,"Доля сделок в расчете, %","Trades Volume in count, %"
9,VolOrders,"Доля заявок в расчете, %","Orders Volume in count, %"

analytics

,tradedate,secid,Numtrades,AvgTradesVol,MinTradePrice,MaxTradePrice,Vol,MinVol,VolShare,VolOrders
0,2023-06-01,RUSFAR,394,381497193,7.20,7.25,1.503099e+11,30000000000,100.00,0.00
1,2023-06-01,RUSFAR1M,8,61406250,7.40,7.41,4.912500e+08,30000000000,1.64,98.36
2,2023-06-01,RUSFAR1W,41,665488415,7.23,7.30,2.728502e+10,30000000000,90.95,9.05
3,2023-06-01,RUSFAR2W,12,300000000,7.30,7.30,3.600000e+09,30000000000,12.00,88.00
4,2023-06-01,RUSFAR3M,0,0,0.00,0.00,0.000000e+00,30000000000,0.00,100.00
5,2023-06-01,RUSFARCNY,91,30573577,0.54,0.75,2.782196e+09,200000000,100.00,0.00

analytics.dates

         from        till
0  2021-01-25  2023-06-01

In [211]:
MOEX.api_description(134, True)

134: Показатели для определения критериев существенного отклонения

Возвращаемые поинтом данные:
securities:
securities.cursor:
securities.dates:

Параметры запроса:
``date``: Дата за которую необходимо вывести данные.
Формат: ГГГГ-ММ-ДД.. Значение по умолчанию: today
``start``: Номер строки (отсчет с нуля), с которой следует начать порцию возвращаемых данных (см. рук-во разработчика).
Получение ответа без данных означает, что указанное значение превышает число строк, возвращаемых запросом.. Значение по умолчанию: 0

Эндпоинт возвращает ограниченное количество записей

Детали: http://iss.moex.com/iss/reference/134
Темплейт: http://iss.moex.com/iss/statistics/engines/stock/deviationcoeffs

In [212]:
print_df(MOEX.request(134))

securities

C:\projects/moex_research\api_lib\main.py:281: UserWarning: К API стучались 100 раз. Возвращены не все данные!!!
  warnings.warn(f"К API стучались {cnt} раз. Возвращены не все данные!!!")

,tradedate,secid,liquidity,sigma,beta,f_plus,f_minus,spread,coeff_c
0,2023-05-31,ABRD,L,0.025114,0.821507,0.000000,0.00,0.00000,0.0
1,2023-05-31,AFKS,L,0.016671,0.823584,0.000000,0.00,0.00000,0.0
2,2023-05-31,AFLT,L,0.023203,1.464660,0.012124,0.50,0.00000,0.0
3,2023-05-31,AGRO,L,0.016906,1.055970,0.010103,0.25,0.00000,0.0
4,2023-05-31,AKGD,L,0.010438,0.000000,0.000000,0.00,0.00000,0.0
5,2023-05-31,AKMB,L,0.002276,0.000000,0.000000,0.00,0.00000,0.0
6,2023-05-31,AKME,L,0.010555,0.000000,0.000000,0.00,0.00000,0.0
7,2023-05-31,AKMM,L,0.000261,0.000000,0.000000,0.00,0.00000,0.0
8,2023-05-31,AKQU,N,0.014600,0.000000,0.000000,0.00,0.01972,0.0
9,2023-05-31,AKRN,L,0.009281,0.287563,0.000000,0.00,0.00000,0.0

securities.dates

         from        till
0  2011-01-24  2023-05-31

In [210]:
MOEX.all_api()

5 Список бумаг торгуемых на московской бирже.
13 Получить спецификацию инструмента.
24 Получить сводные обороты по рынкам
26 Получить интервал дат, доступных в истории для рынка по заданному режиму торгов.
28 Получить глобальные справочники ISS.
32 Получить таблицу инструментов по режиму торгов.
33 Получить таблицу инструментов торговой сессии по рынку в целом.
34 Получить все сделки по выбранному режиму торгов.
35 Получить все сделки рынка.
40 Получить доступные торговые системы.
41 Получить описание и режим работы торговой системы.
42 Получить список рынков торговой системы.
43 Получить справочник режимов торгов рынка.
44 Получить описание: словарь доступных режимов торгов, описание полей публикуемых таблиц данных и т.д.
45 Получить справочник групп режимов торгов.
46 Получить свечи указанного инструмента по выбранному режиму торгов.
48 Получить период дат рассчитанных свечей.
49 Получить описание режима торгов.
50 Получить описание группы режимов торгов.
52 Получить данные по конкретному инструменту рынка.
53 Получить данные по указанному инструменту на выбранном режиме торгов.
55 Получить сделки по инструменту.
56 Получить все сделки указанного инструмента по выбранному режиму торгов.
61 Получить интервал дат в истории для указанного рынка и бумаги.
62 Получить историю по всем бумагам на рынке за одну дату.
63 Получить историю по одной бумаге на рынке за интервал дат.
64 Получить историю торгов для всех бумаг на указанном режиме торгов отфильтрованных по дате.
65 Получить историю торгов для указанной бумаги на указанном режиме торгов за указанный интервал дат.
66 Получить интервал дат в истории, за которые доступна указанная бумага на рынке на указанном режиме торгов.
83 Получить даты, за которые доступны данные на указанных рынке и торговой системе.
89 Получить данные по кривой бескупонной доходности(Прекращены расчеты с 2018-01-03)
95 Получить текущее значение оборотов торговой сессии по рынкам торговой системы
96 Получить текущее значение оборота по рынку
100 Получить описание полей для запросов оборотов по рынку/торговой системе.
114 Список годов, за которые существуют ссылки на файлы с архивом сделок и исторической биржевой информацией. datatype может принимать значения securities или trades.
115 Список месяцев в году, за которые существуют ссылки на файлы с архивом сделок и исторической биржевой информацией. datatype может принимать значения securities или trades.
118 Список неторгуемых инструментов с указанием интервалов торгуемости по режимам
119 Получить данные по листингу бумаг в историческом разрезе по указанному режиму
123 Информация по техническому изменению торговых кодов
127 Группы ценных бумаг
128 Группа ценных бумаг
129 Коллекции ценных бумаг входящие в группу
130 Коллекция ценных бумаг входящие в группу
131 Описание инструментов
134 Показатели для определения критериев существенного отклонения
146 Индексы фондового рынка
147 Аналитические показатели за дату
148 Список тикеров за все время торгов
155 Получить свечи указанного инструмента по дефолтной группе режимов.
156 Интервалы свечей, доступных к запросу по ФИ
157 Получить свечи указанного инструмента по выбранной группе режимов торгов.
159 Капитализация фондового рынка
160 Список индексов в которые входит бумага
161 Список режимов обобщенной информации по фондовому рынку
162 Обобщенная информация по фондовому рынку
165 РЕПО ГЦБ объемы (УСТАРЕЛО)
166 РЕПО ГЦБ детали (УСТАРЕЛО)
168 Курсы ЦБРФ
169 Средневзвешенные ставки по операциям центрального банка
171 Cписок акций, по которым рассчитывается рыночная котировка
172 Коэффициенты корелляции фондового рынка
178 Ставки РЕПО аукционов (ГЦБ)
179 Описание полей для запроса ставок РЕПО аукционов (ГЦБ)
191 Новости биржи
192 Новость сайта
193 Мероприятия биржи
194 Контент мероприятия биржи
195 Агрегированные показатели рынка облигаций
196 Описание колонок по агрегированным показетелям рынка бондов
205 Описание колонок бумаг входящих в индекс
214 Агрегированные итоги торгов за дату по рынкам
634 Кривые безкупонной доходности
649 Текущие цены бумаг
711 Индикативные курсы валют срочного рынка
712 Индикативный курс валют срочного рынка
715 Фиксинги Московской биржи
716 Фиксинги Московской биржи
758 Справочник дроблений и консолидаций бумаг фондового рынка
767 Сводная статистика по клиентам с самым высоким нетто-потоком. Детали https://fs.moex.com/f/10374/netflow2-demo-en.html
769 Сводная статистика по клиентам с самым высоким нетто-потоком. Запрос возможен с лагом -15 дней от текущего для 1 эшелона. Детали https://fs.moex.com/f/10374/netflow2-demo-en.html
783 История изменения параметров КБД (Кривая Бескупоной Доходности).
791 Получить историю рассчитанных доходностей для всех бумаг на указанном режиме торгов отфильтрованных по дате.
793 Получить историю доходностей по одной бумаге на рынке за интервал дат.
795 Получить историю доходностей для всех бумаг на указанном режиме торгов отфильтрованных по дате.
797 Получить историю доходностей для указанной бумаги на указанном режиме торгов за указанный интервал дат.
807 Сводные остатки по фьючерсам на физ. и юр. лица.
809 Сводные остатки по фьючерсам на физ. и юр. лица. Запрос возможен с лагом -15 дней, по коду фьючерса
811 Список сессий доступных в итогах торгов. Только для фондового рынка!
813 Получить историю по всем бумагам на рынке за одну дату.
815 Получить историю торгов для указанной бумаги на указанном режиме торгов за указанный интервал дат.
817 Получить историю по одной бумаге на рынке за интервал дат.
821 Получить историю торгов для всех бумаг на указанном режиме торгов отфильтрованных по дате.
823 Промежуточные "Итоги дня". Только для фондового рынка
839 Бюллетени для индексов
843 RUSFAR расшифровка показателей
859 Будущие ставки для ценообразования нестандартных инструментов (деривативов)
861 Будущие ставки для ценообразования нестандартных инструментов (деривативов)
873 Опционные серии
877 Опционные серии
879 Объем торгов для опционной серии
881 Доска опционов
883 Открытые позиции по опционной серии
885 Объем торгов для опционной серии
923 Календарь расчетных дней
927 Своп-кривые на рынке СПФИ
933 НКД на конец месяца

### Итого.

1. Убедились, что написанная библиотека для удобного запроса данных с апи работает. Вам даже не нужно знать как работать с REST-API.
2. Множество поинтов дублирует друг друга, по сути все можно смело разделить на 3.
3. К сожалению, нет доступа к тиковым данным истории. Можно запросить данные только за последнюю сессию.
4. Можно выцепить много полезной инфы из коротких свечек (минута), есть показатели ликвидности, статитстика по крупнякам, доходностям, расшифровок бенчмарков, остаткам на счетах по срочке, истории по площадкам.
5. Нет доступа к ордерлогам, к сожению, также платно.
6. Из минусов - библиотека не юзает асинхронку. Боюсь ее использование может вызвать отклонение запросов со стороны Биржи (ddos).

#### В следующей - заключительной части поиграем с данными. Порисуем графики, посмотрим корреляции между спотом и остатками срочки, крупняками; прочими интересными наблюдениями.


### Надеюсь, данная библиотека будет полезна для вас.